### ISSUE TITLE
Duplicate locale(s) folder

### ISSUE THREAD

**Issue by kytwb** [actionhero/actionhero#1016]
# Duplicate locale(s) folder
Presence of two locale folders after running the tests: `./locale` and `./locales`.

- ActionHero Version: `16.0.0`
- Node.js Version: `6.10.0`
- Operating System: `Ubuntu`

# Steps to reproduce your error
- Make a new actionhero project with `./node_modules/.bin/actionhero generate`
- Run the tests through `npm test`
- A `./locale` folder will be created

**Comment by kytwb** [comment]
My bad, this is not a bug as that's the specified behavior for the test environment (in `config/api.js`).  
It might be confusing for other people as well, what can be done to enhance this?

**Comment by kytwb** [comment]
I see something was done to handle this [here](https://github.com/actionhero/actionhero/blob/master/config/api.js#L79) to use the OS temp directory. The issue is related to npm/npm#4531.

**Comment by evantahler** [comment]
Fascinating and terrible. 
I agree that the folder names should be the same [[ https://github.com/actionhero/actionhero/commit/60e8d71af480a930d26828d837a89b2af048f138 ]], but I don't belive that it would be actionhero's place to mess with the TMPDIR.

Using `npm test` on OSX sees this working OK, I wonder if this is Ubuntu specific?

**Comment by crrobinson14** [comment]
Does this have to be more than a simple typo?

    config/api.js:        'locale': [path.join(__dirname, '/../locales')]
    config/api.js:        'locale': [require('os').tmpdir() + require('path').sep + 'locale']

One uses singular, the other, plural.

**Comment by evantahler** [comment]
Yep, it was a typo... and that was solved in the commit referenced above.   That doesn't change the fact that `os.tmpdir()` doesn't work, sometimes, if you use NPM

**Comment by kytwb** [comment]
Closing as not related to Actionhero.
Solved using the solution mentionned in https://github.com/npm/npm/issues/4531#issuecomment-272534113:

> Just set `npm config set unsafe-perm true`

**Comment by kytwb** [comment]
I talked a bit too fast. This doesn't work for me.  
What about implementing https://github.com/avajs/find-cache-dir?

**Comment by evantahler** [comment]
It looks like we only use `os.tmpdir` in tests.  I'm reluctant to require a new package just for testing.  We can move all of our test dirs inside of the test folder (local to the project), and that should clear this up.

**Comment by kytwb** [comment]
@evantahler maybe we can just follow their ~convention and store temp things in `./node_modules/.cache/actionhero`?

**Comment by evantahler** [comment]
I don't think we are creating a cache, this is really just throw-away data for testing.

**Comment by evantahler** [comment]
@kytwb I'm looking to you for a pull request, so show us what implementation you think is best, and we can talk about it there!

**Comment by kytwb** [comment]
Just a heads up, I haven't forgotten about this, just been busy with work and life.  
Will come back with a PR soon!

**Comment by evantahler** [comment]
@kytwb I'm closing this for now... and because the locale tests don't create a new directory :D

Changed as part of https://github.com/actionhero/actionhero/pull/1036
