### ISSUE TITLE
Initializer won't run if filename same a plugin's initializer

### ISSUE THREAD

**Issue by kytwb** [actionhero/actionhero#1019]
# Name of Issue
Description of Issue

- ActionHero Version: 16.x.x
- Node.js Version: 6.x.x
- Operating System: Ubuntu

# Steps to reproduce your error
- Install and link `ah-sequelize-plugin`
- Create an initializer in `/initializer/sequelize.js`

Renaming `/initializer/sequelize.js` to `/initializer/database.js` works.

**Comment by evantahler** [comment]
This is the behavior we want!
We've recently *explicitly* denied initializers with duplicated names: https://github.com/actionhero/actionhero/issues/1006 + https://github.com/actionhero/actionhero/pull/1007

We want to make it very clean which file is working on/with each part of the `api` namespace, and if it has problems, crashing.

**Comment by evantahler** [comment]
Perhaps there is something wrong with how `ah-sequelize-plugin` works?  
cc @l0oky
