### ISSUE TITLE
Bug: resque multiworker uses redis after the client connection is closed

### ISSUE THREAD

**Issue by vladbalmos** [actionhero/actionhero#1034]
# Bug: resque multiworker uses redis after the client connection is closed

- ActionHero Version: `master`
- Node.js Version: `4.5.0`
- Operating System `Ubuntu 14.04.4`

The tests for the project i'm working on randomly fail due to a synchronization issue between the way the resque multiworker is started and the Redis initializer. I haven't found a way to replicate it consistently but I'll do my best to show how it happens:

When running the `before` phase of a test suite the redis & resque initializers are started. At this point, the multiworkers schedules some cleanup work on startup:

    node-resque/lib/multiWorker.js:211
        -> calls self.checkWrapper
       -> calls self.checkWorkers
       -> calls worker.untrack()
       -> which in turn calls Redis.del

The entire process is set to run after a timeout has passed, but before this timeout is reached, the test suite has executed and has entered its tear down phase (after) at which point the Redis client gets disconnected, shortly after this, the multiworker cleanup timeout has passed and the operations are executed using the disconnected Redis client, leading to the following error:

    Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot DEL

I added debug statements to track this and you can see below that the order of the operations is not as it should be:

Expected order of execution:

0. Test suite setup (before)
1.  Redis connections are opened (redis initializer)
2. Multiworker is started - does cleanup - removes from Redis whatever it needs to (resque initializer)
3. Tests are run
4. Test suite tear down (after)
5. Multiworker gets stopped
6. Redis clients are disconnected

Actual order of execution:

0. Test suite setup (before)
1.  Redis connections are opened (redis initializer)
2. Multiworker is started - starts the cleanup process
3. Tests are run
4. Test suite tear down (after)
5. Multiworker gets stopped
6. Redis clients are disconnected
**7. Multiworker cleanup is still running** 
    
This issue came up after the stop phase of the Redis initializer disconnects the clients, which wasn't the case in the previous versions.

Please see the output of my tests, lines starting with "--------" were added by me. This is the location of each console.log statement:

    initializers/resque.js:138 - console.log('------------------ starting multiworker'); 
    node_modules/node-resque/lib/worker.js:384 - console.log('--------------- deleting ' + key)
    initializers/redis.js:25 - console.log('------------------------ starting connection ----------------------------')
    initializers/redis.js:170 - console.log('------------------------ closing connection ----------------------------');

I am pretty sure this is related to #1028 

    OK

    broadcastGetData Action Tests
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------ starting multiworker
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
        ✓ should return error if user does not exist
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should return error if redis fails
        ✓ should return error if broadcastData is empty
        ✓ should return broadcastData for viewer
        ✓ should return broadcastData for broadcaster
        ✓ should return broadcastData for viewer with messages
        ✓ should return broadcastData for viewer with his current question (39ms)
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should return broadcastData with questions for broadcaster (38ms)
        ✓ should return broadcastData with current promo URL
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------

    joinBroadcast Action Tests
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------ starting multiworker
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should return error if user does not exist
        ✓ should return error if broadcast does not exist
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
        ✓ should join broadcast as viewer
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
        ✓ should join broadcast as broadcaster
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should return messages on join
        ✓ should return messages on join
        ✓ should return the current question on  join for viewer 
        ✓ should return the broadcast questions on join for broadcaster
        ✓ should return the current promo URL on join
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------

    messageSend Action Tests
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------------ starting connection ----------------------------
    ------------------ starting multiworker
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should return error if user is not authenticated
        ✓ should send the message to special users
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
        ✓ should broadcast the message to all users
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
    --------------- deleting chat-manager:stat:failed:be6700bb1d92:11567+1
    --------------- deleting chat-manager:stat:processed:be6700bb1d92:11567+1
        ✓ should send the message to users with specific connection IDs
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------
    ------------------------ closing connection ----------------------------

    promoUrlSet Action Tests
    --------------- deleting chat-manager:worker:be6700bb1d92:11567+1:*:started
        1) "after all" hook
        - should return an error if user is not authenticated
        - should return an error if user is a viewer
        - should return an error if url has a wrong format
        - should return an error if add promo URL fails
        - should return promo URL data when url is added with success
        - should return empty object when a promo URL is cleared
        questionAsk Action Tests
        questionChange Action Tests
        - should return error if user is not authenticated
        - should return error if question is empty
        - should return error if question is not a string
        - should return error if user is not a viewer
        - should add the question with success
        - should return error if user is not authenticated
        - should return error if question is not a string
        - should return error if question is not found
        - should return error if question has definitive status
        - should change the question text successfully
        - should return internal server error if redis fails
        - should return error if questionID is not a string
        - should return error if status is invalid
        - should return error if the question does not exist
        - should return error if question status change is attempted early
        - should return error if redis fails on change status
        - should change the question status and add dateAnswered
        - should change the question status and delete the current questionID for user
        usersGetAll Action Tests
        usersGetCount Action Tests
        - should return error if user is not authenticated
        - should return error if user is viewer
        - should return user details for broadcaster
        - should return error if redis fails
        - should return error if user is not authenticated
        - should return user count for broadcaster
        - should return user count for viewer
        - should return error if redis fails

    22 passing (4s)
    32 pending
    1 failing

    1) messageSend Action Tests "after all" hook:
        Uncaught Error: fakeredis: You've closed this connection with QUIT, cannot DEL
        at CLOSED (node_modules/fakeredis/lib/connection.js:244:11)
        at push (node_modules/fakeredis/lib/connection.js:16:5)
        at RedisClient.cl.send_command (node_modules/fakeredis/main.js:140:7)
        at RedisClient.(anonymous function).RedisClient.(anonymous function) (node_modules/fakeredis/node_modules/redis/lib/commands.js:45:25)
        at node_modules/node-resque/lib/worker.js:384:105
        at node_modules/async/dist/async.js:3686:9
        at replenish (node_modules/async/dist/async.js:882:17)
        at iterateeCallback (node_modules/async/dist/async.js:867:17)
        at node_modules/async/dist/async.js:840:16
        at node_modules/async/dist/async.js:3691:13
        at apply (node_modules/async/dist/async.js:21:25)
        at node_modules/async/dist/async.js:56:12
        at node_modules/fakeredis/main.js:184:5
        at null._onTimeout (node_modules/fakeredis/lib/connection.js:343:18)

**Comment by evantahler** [comment]
Can you also share your config/redis and config/tasks?  That will be very helpful.  Do you see the same behavior when using a real redis connection?

**Comment by evantahler** [comment]
For example, here's a test suite you can run in isolation against a new actionhero project.  It explicitly runs delayed tasks, a scheduler, multi worker, etc.  It' runs a task N times in a loop. Given this configuration, I can't get the above error to occur:

```js
var chai = require('chai')
var dirtyChai = require('dirty-chai')
var async = require('async')
var expect = chai.expect
chai.use(dirtyChai)

var ActionheroPrototype = require('actionhero')
var actionhero = new ActionheroPrototype()
var api

describe('actionhero Tests', () => {
  before((done) => {
    actionhero.start((error, a) => {
      expect(error).to.be.null()
      api = a
      done()
    })
  })

  after((done) => {
    actionhero.stop(function (error) {
      expect(error).to.be.null()
      done()
    })
  })

  describe('tasks', () => {
    var taskOutput = []

    before((done) => {
      api.resque.multiWorker.options.minTaskProcessors = 1
      api.resque.multiWorker.options.maxTaskProcessors = 1
      api.config.tasks.queues = ['*']
      api.config.tasks.scheduler = true
      api.config.tasks.timeout = 100
      api.config.tasks.checkTimeout = 50

      api.tasks.tasks.slowTask = {
        name: 'slowTask',
        description: 'task: slowTask',
        queue: 'test',
        frequency: 0,
        plugins: [],
        pluginOptions: {},
        run: (api, params, next) => {
          taskOutput.push('slowTask')
          setTimeout(next, 1000)
        }
      }

      api.tasks.jobs.slowTask = api.tasks.jobWrapper('slowTask')

      api.resque.startScheduler(() => {
        api.resque.multiWorker.start(() => {
          done()
        })
      })
    })

    after((done) => {
      delete api.tasks.tasks.slowTask
      delete api.tasks.jobs.slowTask
      api.config.tasks.queues = []
      api.config.tasks.scheduler = false
      api.resque.multiWorker.options.minTaskProcessors = 0
      api.resque.multiWorker.options.maxTaskProcessors = 0
      done()
    })

    var times = 20
    for (var i = 1; i <= times; i++) {
      it(`enqueues and runs a delayed task (${i})`, (done) => {
        var jobs = []

        jobs.push((next) => {
          var time = new Date().getTime() + 1000
          api.tasks.enqueueAt(time, 'slowTask', {}, (error) => {
            expect(error).to.be.null()
            next()
          })
        })

        jobs.push((next) => {
          setTimeout(next, 1000)
        })

        jobs.push((next) => {
          taskOutput.forEach((e) => {
            expect(taskOutput[0]).to.equal('slowTask')
          })
          next()
        })

        async.series(jobs, done)
      }).timeout(3000)
    }
  })
})

```

**Comment by vladbalmos** [comment]
With an actual Redis server the issue doesn't come up; below are the requested config files. I will run your test case as soon as I have some spare time. Thanks for looking into this!

config/redis.js:

    var host     = process.env.REDIS_HOST || '127.0.0.1';
    var port     = process.env.REDIS_PORT || 6379;
    var db       = process.env.REDIS_DB   || 0;
    var password = process.env.REDIS_PASS || null;

    exports['default'] = {
      redis: function (api) {

        // konstructor: The redis client constructor method
        // args: The arguments to pass to the constructor
        // buildNew: is it `new konstructor()` or just `konstructor()`?

        if (process.env.FAKEREDIS === 'false' || process.env.REDIS_HOST !== undefined) {

          return {
            '_toExpand': false,
            client: {
              konstructor: require('ioredis'),
              args: [{ port: port, host: host, password: password, db: db }],
              buildNew: true
            },
            subscriber: {
              konstructor: require('ioredis'),
              args: [{ port: port, host: host, password: password, db: db }],
              buildNew: true
            },
            tasks: {
              konstructor: require('ioredis'),
              args: [{ port: port, host: host, password: password, db: db }],
              buildNew: true
            }
          };

        } else {

          return {
            '_toExpand': false,
            client: {
              konstructor: require('fakeredis').createClient,
              args: [port, host, {fast: true}],
              buildNew: false
            },
            subscriber: {
              konstructor: require('fakeredis').createClient,
              args: [port, host, {fast: true}],
              buildNew: false
            },
            tasks: {
              konstructor: require('fakeredis').createClient,
              args: [port, host, {fast: true}],
              buildNew: false
            }
          };

        }
      }
    };

config/tasks.js

    exports['default'] = {
      tasks: function (api) {
        return {
          // Should this node run a scheduler to promote delayed tasks?
          scheduler: (process.env.NODE_ENV == 'test') ? false : true,
          // what queues should the taskProcessors work?
          queues: ['*'],
          // Logging levels of task workers
          workerLogging : {
            failure   : 'error', // task failure
            success   : 'info',  // task success
            start     : 'info',
            end       : 'info',
            cleaning_worker : 'info',
            poll      : 'debug',
            job       : 'debug',
            pause     : 'debug',
            internalError : 'error',
            multiWorkerAction : 'debug'
          },
          // Logging levels of the task scheduler
          schedulerLogging : {
            start     : 'info',
            end       : 'info',
            poll      : 'debug',
            enqueue   : 'debug',
            reEnqueue : 'debug',
            working_timestamp : 'debug',
            transferred_job   : 'debug'
          },
          // how long to sleep between jobs / scheduler checks
          timeout: 5000,
          // at minimum, how many parallel taskProcessors should this node spawn?
          // (have number > 0 to enable, and < 1 to disable)
          minTaskProcessors: 1,
          // at maximum, how many parallel taskProcessors should this node spawn?
          maxTaskProcessors: 5,
          // how often should we check the event loop to spawn more taskProcessors?
          checkTimeout: 500,
          // how many ms would constitue an event loop delay to halt taskProcessors spawning?
          maxEventLoopDelay: 5,
          // When we kill off a taskProcessor, should we disconnect that local redis connection?
          toDisconnectProcessors: true,
          // Customize Resque primitives, replace null with required replacement.
          resque_overrides: {
            queue: null,
            multiWorker: null,
            scheduler: null
          }
        };
      }
    };

    exports.test = {
      tasks: function (api) {
        return {
          timeout: 100,
          checkTimeout: 50
        };
      }
    };

**Comment by vladbalmos** [comment]
I forgot to mention that the tests are running inside a Docker container

**Comment by vladbalmos** [comment]
Running your test on a clean install of actionhero passes, no problem. If I add the test to my project and run it I get this everytime:

   actionhero Tests
     tasks
       ✓ enqueues and runs a delayed task (1) (1015ms)
       ✓ enqueues and runs a delayed task (2) (1020ms)
       ✓ enqueues and runs a delayed task (3) (1015ms)
       ✓ enqueues and runs a delayed task (4) (1013ms)
       ✓ enqueues and runs a delayed task (5) (1012ms)
       ✓ enqueues and runs a delayed task (6) (1014ms)
       ✓ enqueues and runs a delayed task (7) (1024ms)
       ✓ enqueues and runs a delayed task (8) (1017ms)
       ✓ enqueues and runs a delayed task (9) (1037ms)
       ✓ enqueues and runs a delayed task (10) (1015ms)
       ✓ enqueues and runs a delayed task (11) (1014ms)
       ✓ enqueues and runs a delayed task (12) (1017ms)
       ✓ enqueues and runs a delayed task (13) (1013ms)
       ✓ enqueues and runs a delayed task (14) (1019ms)
       ✓ enqueues and runs a delayed task (15) (1012ms)
       ✓ enqueues and runs a delayed task (16) (1014ms)
       ✓ enqueues and runs a delayed task (17) (1013ms)
       ✓ enqueues and runs a delayed task (18) (1013ms)
       ✓ enqueues and runs a delayed task (19) (1011ms)
       ✓ enqueues and runs a delayed task (20) (1012ms)
     1) "after all" hook
 
 
   20 passing (22s)
   1 failing
 
   1) actionhero Tests "after all" hook:
      Uncaught TypeError: Cannot read property 'frequency' of undefined
       at Object.api.tasks.jobWrapper.validateTask.enqueueRecurrentJob (node_modules/actionhero/initializers/tasks.js:244:17)
       at null._onTimeout (node_modules/actionhero/initializers/tasks.js:102:22)
 
 I don't understand. Should I have done something after the upgrade? Update some files maybe?

**Comment by vladbalmos** [comment]
I have discovered that if I modify the `stopPriority` property of the Redis initializer to 10000 the issue disappears. 

Shouldn't the Redis initializer be the last one stopped? If my application initializers have a priority value of over 1000 (as stated in the docs) and in the stop phase of one of those I publish a message on a Redis channel, it will fail, since the Redis initializer is stopped before mine is (Redis initializer stop priority is 999).

**Comment by evantahler** [comment]
Awesome research, and yes! That makes sense!
We've tried to keep all `internal` initializers with a priority under 1000, but I think this is a good special case.   

https://github.com/actionhero/actionhero/commit/dcf6dd9b529c0e844ee0bc821abe7fa75ef9aef2
