### ISSUE TITLE
cluster_pidfile not removed during Gracefully stopping 

### ISSUE THREAD

**Issue by bbaga** [actionhero/actionhero#1064]
I was wondering why isn't the cluster_pidfile removed when the cluster shuts down gracefully.
After starting a cluster with some workers I wait for the boot sequence to finish, then press CTRL+C

```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping web-api ... done  (docker stuff)
```

The pid file is still there and I get an error of course:
```
error:  Error: actionHeroCluster already running (pid xx)
```

I looked into the code and it seems there isn't even an attempt to remove the cluster's pid file and that made me wonder why is it being kept on shut down.

v16.0.0

**Comment by evantahler** [comment]
Excellent idea! 
I've implemented that here https://github.com/actionhero/actionhero/pull/1065
