### ISSUE TITLE
Separation of placeholder data from params

### ISSUE THREAD

**Issue by jkelkar** [actionhero/actionhero#1073]
# Name of Issue
Description of Issue
Currently "data.params" include data from placeholders in the URL and also params passed in.
Often data from placeholders is readonly (used to get to a specific resource) and params data is often used to update or create a record. It would be helpful if these data could be presented separately as "data.urldata and data.params respectively - or something along these lines".

- ActionHero Version: `latest`
- Node.js Version: `any`
- Operating System `any`

No error, just extra work to automate sql code generation using node-sql. This change would also benefit most others.
---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
Can you be more specific, and perhaps include a code sample?  What data from URLs is being included?  Are you perhaps asking to filter GET query params from actions?

**Comment by jkelkar** [comment]
As an example, for this route:
```
put: [
   { path: '/:table/:id', action: 'tableEdit' } // params: {name: 'me', age: 12}
]
```
It would be useful is 'table' and 'id' with values were provided separately from 'name' and 'age'. Currently they all appear in data.params.

**Comment by evantahler** [comment]
I don't think I follow here... perhaps an example of how you would use that separation (between `params` and `query`) in an action would help?  

Since your params are unique, (table, field, etc), does the distinction of how they came to be passed in matter?  Does that also mean that you wouldn't want `/api/tableEdit?table=table&field&field&val=val&name=me&age=21` to work?

Also, today, if you are curious about the URL, you can inspect `data.connection.rawConnection.params` to see the query https://www.actionherojs.com/docs/servers/web#the-connection-object

**Comment by jkelkar** [comment]
>  Does that also mean that you wouldn't want `/api/tableEdit?table=table&field&field&val=val&name=me&age=21 `to work?

Actually yes, I would not because the placeholders in the path
`/:table/:field/:val`
have a significantly different meaning from those provided in the query or params. The first is used to locate or identify the resource and the second acts on it. Thinking of automation, and not limiting your self to just one path, I can see a situation where a code generator would be able to use the path and the values collected to automatically access the DB to do the necessary.

As in Express.js, there should a separation between: params, body and query.

**Comment by gcoonrod** [comment]
@jkelkar Can you provide a more detailed example? I'm having trouble understanding how having the path variables separated from the query variables in `params` is valuable. As @evantahler said they are all named variables so you should know how to address them without issue. 

In addition a path like the one you described seems nonsensical... its just three variables. Did you mean to use `/table/:table/field/:field/var/:var`?

**Comment by jkelkar** [comment]
Actually:
`/:table/:field/:val`
makes sense. It would be the last 3 segment route in this method. Here I choose to mean I look for field with that value. 

So say I want to update a row in table 'orderhead', where 'id' equals 20.
I would use
`/orderhead/id/20` 
and the payload would contain the fields that are being updated. say `subtotal=12.23`, `tax=...` and `total=...`. 
The code processing this request already knows the path and that `table`, `field` and `val` are part of the url and hence are to be used in the `where` part of the query and the rest of the payload (in what is traditionally called the body) is to be used in the `set` part (in this example:  `update orderhead set subtotal=12.23, ... where id=20`).

If this still seems nonsensical, we can drop the whole thing.

**Comment by gcoonrod** [comment]
Perhaps nonsensical was a poor choice of words. I apologize. Let me explain
my confusion. The path you have described would match any three part path
(e.g. /users/bob/listBeers, /orders/:id/items, /city/Stockholm/bars) which
could cause a conflict with other routes that you've registered in
ActionHero. If, however, you'll only ever register a single route like the
one you've described then you could achieve the result you desire by using
action middleware to alter the params object prior to the action running.

**Comment by jkelkar** [comment]
I like with your suggestion. You have a very good point, one I had not thought of. 
I only have one route of this nature for a method and given the # of segments in a route.

I shall use middleware to extract what I need out of params and also to build the query. Thanks.

**Comment by gcoonrod** [comment]
I'm glad I could help. If you have any other questions please feel free to
join our Slack channel.
