### ISSUE TITLE
How to set global data for request-response cycle in a middleware

### ISSUE THREAD

**Issue by antonsapyanov** [actionhero/actionhero#1091]
I want to set current user object in the authentication middleware, so it will be accessible during all request-response cycle. I saw, that someone saves it as `api` global property, like that: `api.current_user`. But I guess, that it will lead to errors, because another request can override this object while previous one is not finished yet. Is it ok to modify `data` object in the middleware? Because I haven't found any suggestion on that in the documentation. 

```
module.exports = {
	loadPriority:  1000,
	startPriority: 1000,
	initialize: function (api, next) {
		const  authenticationMiddleware = {
			name: 'authentication Middleware',
			priority: 100,
			global: true,
			preProcessor: function (data, next) {
				if (data.actionTemplate.authenticated === true) {
					const auth_token = data.connection.rawConnection.req.headers.authorization;
					api.users.authenticate(auth_token, function (error, user) {
						if(error) {
							data.connection.rawConnection.responseHttpCode = 401;
								return next(new Error('Session Expired', 401));
						}

                                                // IS IT OK TO DO SOMETHING LIKE THAT?
						data.current_user = user;
						return next();
					})
				} else {
					return next()
				}
			}
		};
		api.actions.addMiddleware(authenticationMiddleware);
		next()
	}
};
```

- ActionHero Version: `17.1.0`
- Node.js Version: `8.2.1`

**Comment by evantahler** [comment]
Save it to the `data` object!  This is only in-scope for the current connection.  As you have it, `data.current_user = user` is great.

Here are some examples which do a similar thing, loading session data from redis and adding it to `data.session. https://github.com/actionhero/actionhero-angular-bootstrap-cors-csrf/blob/master/initializers/session.js#L58
