### ISSUE TITLE
Verb not found when calling an action

### ISSUE THREAD

**Issue by Martinlck** [actionhero/actionhero#1096]
# Verb not found
Description of Issue

- ActionHero Version: latest
- Node.js Version: `v6.11.1`
- Operating System `Ubuntu 14`

# Steps to reproduce your error
- Make a new actionhero project with `./node_modules/.bin/actionhero generate`
- create an action with at least one parameter
- use action hero client to connect to the socket server
- use method actionWithParams
- action hero server code flow goes to error verbNotFound
---

Hello, I upgraded to latest AH, I was using v15 before, and I started having some issues. 
On my test suite I use the actionhero client to call the actions within my socket server, and I use the actionWithParams method to call the respective actions. For some reason that triggers the code that is on errors for verbNotFound, which somehow on my local environment that is not sent back as the reply, but on CircleCI when doing my build process, on the tests that error is return to the client and my tests fails.

Not sure if this is a problem on the AH client or maybe I'm doing something wrong...

Thanks for maintaining such an amazing product!!! I really appreciate it.

**Comment by Martinlck** [comment]
Ok, after testing with the specHelper, this only happens when using the action hero client.

**Comment by Martinlck** [comment]
Ok never mind, I found the cause of the issue, is on my end.
I did not add the locale folder on CI, and then on the parseRequest function it matches the string error message and instead of getting the expected locale message it was just getting the raw error code verbNotAllowed. Maybe that could be improved? using some error code or something? I mean if there is a different locale with different text or in different language it will cause the same issue since the function parseRequest checks explicitly for the English text.

Let me know your ideas, if you think we could do something I can create a PR.

I can't thank you guys enough for the amazing project and for it to be open source!

**Comment by evantahler** [comment]
I'm glad you like working with ActionHero!

We use the `i18n` package to handle our translations, and as far as I can tell, this is the only behavior they support (returning a default string/message when none is found).  I've asked about it here https://github.com/mashpie/i18n-node/issues/333
