### ISSUE TITLE
Backport documentation from master

### ISSUE THREAD

**Issue by gcoonrod** [actionhero/actionhero#1110]
# Name of Issue
The JSDoc comments added as a part of the Promise work only apply to the new code structure. It is desirable from a community support perspective to provide the same type of documentation for the last major revision of ActionHero.

**Comment by evantahler** [comment]
This can be done against the `v17` branch https://github.com/actionhero/actionhero/tree/v17

**Comment by gcoonrod** [comment]
I am marking this issue as complete after #1126 was merged

**Comment by evantahler** [comment]
There's still a bit of work to do to add the namespace declarations to the top of each initializer file.  The example I made was https://github.com/actionhero/actionhero/commit/8e6d965b5736a78a6be97b826e140359c115a75c#diff-a3807627aca8240ebff7870d0c3742d0

They won't show up on the site until that is complete. https://docs.actionherojs.com/v17.1.0/

**Comment by gcoonrod** [comment]
Ah, good catch!

**Comment by evantahler** [comment]
solved by https://github.com/actionhero/actionhero/pull/1144
