### ISSUE TITLE
`npm install actionhero` failed with npm@5.4.2

### ISSUE THREAD

**Issue by ChangJoo-Park** [actionhero/actionhero#1139]
# Name of Issue
Description of Issue
failed install actionhero with npm version 5.4.2 

```
node ./cyclic.js

npm ERR! Cannot read property 'pause' of undefined
```

- ActionHero Version: `18.0.1`
- Node.js Version: `8.4.0`
- Operating System `OSX,  Windows 10`

# Steps to reproduce your error
- install actionhero with `npm install actionhero`

---

# How to fix

install npm 5.3.0

```
npm install -g npm@5.3.0
```

**Comment by evantahler** [comment]
This is a known issue with NPM.  Either upgrading `npm install -g npm` or downgrading your version of NPM will fix it.

https://github.com/npm/npm/issues/18520

**Comment by evantahler** [comment]
I'll leave this issue open for a while so others can find it easily.

**Comment by evantahler** [comment]
closing this now as newer versions of NPM have been released which fix this issue.
