### ISSUE TITLE
Sendfile from buffer or string

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/actionhero#1142]
# Sendfile from buffer or string
There is currently no method for responding to an action/route with a file that is not written to disk.  The `connection.sendFile` method only accepts a path to a static file.  The current workaround is to manually write to the raw connection, which loses any of the middleware goodness that might be in play.

Current workaround:
```
data.toRender = false
data.connection.setHeader('Content-Type', 'application/xml; charset=utf-8')
data.connection.rawConnection.res.end(fileBuffer)
```

Ideally, there would be a method for responding with a file.  @evantahler suggests either a second argument added to `connection.sendFile(string, fromFile)` or perhaps a `connection.sendBufferAsFile` method.

**Comment by evantahler** [comment]
solved by https://github.com/actionhero/actionhero/pull/1166
