### ISSUE TITLE
How to handle altering inputs in `run`

### ISSUE THREAD

**Issue by OscarGodson** [actionhero/actionhero#1146]
# How to handle altering inputs in `run`

When we try to alter the params that get sent back we get an error `"TypeError: Cannot assign to read only property 'X' of object '#<Object>'"`. We're upgrading from an older version (13) and we do this throughout our code. We have close to 60+ actions now and some are fairly complex. I'm looking at how to get around this. 

One thing not in the example is we take the data and put it onto a rabbit queue. We use ActionHero sort of like an API proxy to our services. Part of that means adding onto the data. What would be your suggestion to work around this? Maybe clone data?

- ActionHero Version: `18.0.2`
- Node.js Version: `8.8.0`
- Operating System: `MacOS`

# Steps to reproduce your error
Alter an input property inside the run method like:

```js
module.exports = class accountCreate extends BaseAction {
  constructor () {
    super();
      email: {
        required: true
      }
    }
  }
  async run (data) {
      data.params.email = data.params.email.toLowerCase();
  }
};

```

triggers:

```
TypeError: Cannot assign to read only property 'email' of object '#<Object>'
```

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
Hi Oscar!  Not allowing `data.params` to be altered was an explicit choice made in this PR https://github.com/actionhero/actionhero/pull/1114 solving this bug https://github.com/actionhero/actionhero/issues/1112.  Basically, action middleware's preprocessors can modify params, but after that, nothing can.

In your example, what you are doing actually looks like a great case for an input formatter, which is allowed to modify the params:

```js
module.exports = class accountCreate extends Action {
  constructor () {
    super()
    this.inputs: {
      email: { 
        required: true,
        formatter: (p) => { return p.toLowerCase() }
      }
    }
  }

  async run (data) {
      
  }
};
```
If input formatters are not enough, then yes, you would need to clone the params object: `let editableParams = Object.assign({}, data.params)`

**Comment by evantahler** [comment]
Oh, and remember that one of the great things about using "real" classes is that if you have common behavior in many actions (shared inputs, formatters, etc), you can make a base class which you actions extend from
