### ISSUE TITLE
Compound Action with Shared Inputs code does not work as it should

### ISSUE THREAD

**Issue by SpeedyC86** [actionhero/actionhero#1155]
# Tutorial code not working correctly
Compound Action with Shared Inputs code does not work as it should.
Not returning true in the validator function will create a magical issue that will not run the "run" function code. Please correct the tutorial and make the "should return true if validation passed" bold :) It was hard debugging and trying to find out why the code was not working.

- ActionHero Version: `latest`
- Node.js Version: `8.9.1`
- Operating System: `(Ubuntu 16)`

# Steps to reproduce your error
The code in the run function will not be run.
```
// Compound Action with Shared Inputs//
const {Action, api} = require('actionhero')

class ValidatedAction extends Action {
  constructor () {
    super()
    this.inputs = {
      email: {
        required: true,
        validator: this.emailValidator
      },
      password: {
        required: true,
        validator: this.passwordValidator
      }
    }
  }

  emailValidator (param) {
    if (email.indexOf('@') < 0) {
      throw new Error('that is not a valid email address')
    }
  }

  passwordValidator (param) {
    if (param.length < 4) {
      throw new Error('password should be at least 3 letters long')
    }
  }
}

// the actions
exports.UserAdd = class UserAdd extends ValidatedAction {
  constructor () {
    super()
    this.name = 'userAdd'
    this.description = 'I add a user'
  }

  run (data) {
    // your code here
  }
}

exports.UserDelete = class UserDelete extends ValidatedAction {
  constructor () {
    super()
    this.name = 'userDelete'
    this.description = 'I delete a user'
  }

  run (data) {
    // your code here
  }
}
```
---

**Comment by evantahler** [comment]
Thank you for this!  

I think the best behavior would actually be to allow the behavior you thought was possible in the first place.  Only if a validator returns `false` or throws an error should the param count as invalid.  

PR to update this here https://github.com/actionhero/actionhero/pull/1158

**Comment by evantahler** [comment]
closing in favor of https://github.com/actionhero/actionhero/pull/1158
