### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined (primus dependency)

### ISSUE THREAD

**Issue by rubens21** [actionhero/actionhero#1161]
# Cannot read property 'headers' of undefined
Apparently, the dependency 'primus' was affected by a change in 'websockets' project (
https://github.com/websockets/ws/pull/1099)

I got the error `TypeError: Cannot read property 'headers' of undefined` as soon a client tries to connect to ActionHero app. After investigating it, I figure out that node_modules/primus/transformers/websockets/server.js:37 is expecting this attribute, that was removed from websockets.

Until it is not fixed, here is a workaround:
At node_modules/primus/transformers/websockets/server.js:36 add a new line before the object Spark be created and type:
``` 
socket.upgradeReq = req;
```

I do not know if this repo is the best place to report it. If not, please let me know where can I report it. I am reporting here, though, because I catch it using a brand new Actionhero app.

- ActionHero Version: `16.0.0`
- Node.js Version: `8.9`
- Operating System: `(Ubuntu 16.4)`

# Steps to reproduce your error
- Create an empty Actionhero app (I just have an initializer doing nothing.
- Try to open a websocket connection through a upgrade http connection
```
# Nginx host config
proxy_set_header      Upgrade $http_upgrade;
proxy_set_header      Connection "Upgrade";
```

**Comment by evantahler** [comment]
It seems that this was fixed in Primus in May perhaps?
 https://github.com/primus/primus/commit/fb5cf83ecdab3d8565d13522e14e0c9cd9386819  Can you be sure that you have upgraded all of your dependancies to the latest version?

**Comment by rubens21** [comment]
Forget it, 
I try to reproduce it destroying and up it again, and now it is working. I did not change the package.json. I change the node version though.

I will close the issue, sorry about the false alarm.
