### ISSUE TITLE
How to start a soket server?

### ISSUE THREAD

**Issue by Cheese-Yu** [actionhero/actionhero#1172]
# Name of Issue
Description of Issue

- ActionHero Version: `18.1.1`
- Node.js Version: `x.x.x`
- Operating System: `(OSX, Ubuntu 14, Windows 10, etc)`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- create an action with the following content...

---
192.168.1.60 @ 2018-01-15T08:40:14.217Z - notice: *** Starting ActionHero ***
192.168.1.60 @ 2018-01-15T08:40:14.219Z - notice: environment: development
192.168.1.60 @ 2018-01-15T08:40:14.221Z - notice: pid: 42862
192.168.1.60 @ 2018-01-15T08:40:14.222Z - notice: server ID: 192.168.1.60
192.168.1.60 @ 2018-01-15T08:40:14.222Z - notice: redis is disabled
192.168.1.60 @ 2018-01-15T08:40:14.222Z - notice: Starting server: `web` @ 0.0.0.0:8080
192.168.1.60 @ 2018-01-15T08:40:14.225Z - notice: Starting server: `websocket`
192.168.1.60 @ 2018-01-15T08:40:14.814Z - alert: *** ActionHero Started ***

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
In the file `config/servers/socket.js` set `enabled: true`.

**Comment by Cheese-Yu** [comment]
Thanks!
