### ISSUE TITLE
multiWorkerAction undefined when testing

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/actionhero#1174]
# `multiWorkerAction` undefined when testing
Getting an intermittent `undefined` error while running tests.
```
(node:76928) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'multiWorkerAction' of undefined
    at MultiWorker.api.resque.multiWorker.on (...\node_modules\actionhero\initializers\resque.js:129:193)
    at MultiWorker.emit (events.js:159:13)
    at MultiWorker.checkWraper (...\node_modules\node-resque\lib\multiWorker.js:170:10)
    at <anonymous>
```

The test where this error is being thrown is the basic tests included in the default install (the `env` and `docs` test set).  The test doesn't actually fail, but this error appears in the console while running the tests.

When looking at the code where this error originates, the encapsulating function is marked as `async`, but I don't see any `await` labels, so perhaps there is a missing `await` somewhere?  Adding logging of any sort seems to make the error go away, which would point to it being a timing issue.

- ActionHero Version: `18.1.1`
- Node.js Version: `9.3.0`
- Operating System: `Windows 10`

**Comment by evantahler** [comment]
Can you share more about

>  basic tests included in the default install 

The only tests that should be included are the below:

```js
'use strict'

const chai = require('chai')
const dirtyChai = require('dirty-chai')
const expect = chai.expect
chai.use(dirtyChai)

const ActionHero = require('actionhero')
const actionhero = new ActionHero.Process()
let api

describe('actionhero Tests', () => {
  before(async () => { api = await actionhero.start() })
  after(async () => { await actionhero.stop() })

  it('should have booted into the test env', () => {
    expect(process.env.NODE_ENV).to.equal('test')
    expect(api.env).to.equal('test')
    expect(api.id).to.be.ok()
  })

  it('can retrieve server uptime via the status action', async () => {
    let {uptime} = await api.specHelper.runAction('status')
    expect(uptime).to.be.above(0)
  })
})

```

**Comment by bayssmekanique** [comment]
Yes, I guess I added a `docs` section to mine, but it's more or less the same.
```javascript
const chai = require('chai')
const dirtyChai = require('dirty-chai')
const expect = chai.expect
chai.use(dirtyChai)

const ActionHero = require('actionhero')
const actionhero = new ActionHero.Process()
let api

describe('core', function () {
  this.timeout(100000)
  before(async () => { api = await actionhero.start() })
  after(async () => { await actionhero.stop() })

  it('should have booted into the test env', () => {
    expect(process.env.NODE_ENV).to.equal('test')
    expect(api.env).to.equal('test')
    expect(api.id).to.be.ok()
  })

  it('can retrieve server uptime via the status action', async () => {
    let { uptime } = await api.specHelper.runAction('core:status')
    expect(uptime).to.be.above(0)
  })

  it('can retrieve documentation', async () => {
    let { error } = await api.specHelper.runAction('core:docs')
    expect(error).to.not.exist()
  })
})
```

**Comment by evantahler** [comment]
Some thoughts

1) can you be sure that NODE_ENV=test when you run your test suite?  Are you using cross-env?
2) Are you sure that your test suite uses a different Redis DB than your development environment?
2) That error line eventually references back to `api.config.tasks.workerLogging`... have you modified this property (and lost some keys to the hash) in your test environment?  Did you upgrade from an older version of ActionHero whose config didn't have this data?

**Comment by bayssmekanique** [comment]
1) It is using `cross-env` and the `NODE_ENV` is set to `true`.
2) It is not using a different Redis DB, however, it is using a different namespace.
3) `workerLogging` still default too.

**Comment by bayssmekanique** [comment]
Clearing out the redis database entirely before running tests resolves this issue.
