### ISSUE TITLE
URL parameters in GET request not parsed correctly

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/actionhero#1176]
# URL parameters in GET request not parsed correctly
When a URL is passed into a `GET` request along with other parameters, the parsing for all of the parameters seems to fail.  The order in which the parameters appear also produces different results.

For `http://localhost:8000/oauth/initiate/google?type=login&redirect=http://localhost:3000/oauth/callback/google`, the resulting params object is:
```js
{ type: 'login',
  redirect:
   [ 'http://localhost:3000/oauth/callback/google?type=login',
     'http://localhost:3000/oauth/callback/google' ],
  action: 'oauth:initiate',
  service: 'google',
  apiVersion: 1 }
```

For `http://localhost:8000/oauth/initiate/google?redirect=http://localhost:3000/oauth/callback/google&type=login`, the resulting params object is:
```js
{ redirect: 'http://localhost:3000/oauth/callback/google',
  type: 'login?redirect=http://localhost:3000/oauth/callback/google,login',
  action: 'oauth:initiate',
  service: 'google',
  apiVersion: 1 }
```

- ActionHero Version: `18.1.1`
- Node.js Version: `9.3.0`
- Operating System: `Windows 10`

**Comment by bayssmekanique** [comment]
As an added note, this only appears when using a declared route.  It does not appear when passing in a route through the query routing.

**Comment by evantahler** [comment]
Can you please help create a failing test case for this?  We'll need to see what your routes.js file looks like as well to debug this

**Comment by evantahler** [comment]
Oh, and are you certain that you are URL-encoding your GET params?

**Comment by bayssmekanique** [comment]
Ok, so this turns out be an obscure bug in Postman which seems to only happen when there is a URL in the query parameters and you use a variable as the base route.  Took me a while to track it down.  Sorry for the trouble :-P
