### ISSUE TITLE
Actionhero fails to parse locally scoped IPv6 addresses

### ISSUE THREAD

**Issue by AAUBSS** [actionhero/actionhero#1178]
# Name of Issue: Actionhero fails to parse locally scoped IPv6 addresses
Description of Issue: Actionhero will throw 'failed to parse address' when calling api.utils.parseIPv6URI with an IPv6 address containing an address scope (e.g. ::%eth0). For an overview about scoped addresses see [Wikipedia - IPv6 Address - Scoped literal](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses). The currently used regex to parse incomming IPv6 addresses will fail to match scoped addresses.

- ActionHero Version: `18.1.1`
- Node.js Version: all
- Operating System: all

# Steps to reproduce your error
- Send a request to Actionhero containing a 'x-forwarded-for' header with a scoped IPv6 address
- [alternatively call any other function that relies on api.utils.parseIPv6URI or call it directly with such an address]
- Such an address could be [fe80::1ff:fe23:4567:890a%eth2]:12345

# Workaround / Fix
- Include the scope in the resulting host part of the parsed address by changing the regex
- My current change to get Actionhero working looks like this: `let regexp = new RegExp(/\[([0-9a-f:]+(?:%.+)?)]:([0-9]{1,5})/)`, it will not mess with the match order

# Misc
I saw previous issues with the IPv6 parsing in the project issue history. @evantahler: You stated you might want to include a external lib to handle this. I'm not sure if - and how many of such edge cases potentially exist that are still not covered by the current regex or my extension of it.

**Comment by evantahler** [comment]
Thanks for finding this @AAUBSS!

Please send in a Pull Request with the fix! Please add a failing test here https://github.com/actionhero/actionhero/blob/master/test/utils/utils.js#L115 and then replace the old regex with your update! 

At the time, I don't think we found a good IPv6 parser... but one *might* exist now?  If you can find one, please remove the util function for it!

**Comment by aurasalexander** [comment]
... continuing from my private account.
There are some quite some IPv6 parsers out there, but the ones I've seen seem to dual focus on parsing and manipulating. I don't feel like pulling in another lib with quite some overhead in favor of a 8 character regex change ;-).

**Comment by evantahler** [comment]
Closing in favor of https://github.com/actionhero/actionhero/pull/1179
