### ISSUE TITLE
Using connection pipe throws error after execution

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/actionhero#1183]
# Connection pipe throw error
When I pass a response directly to the `rawConnection` the request completes correctly, however an error is thrown immediately afterward.

- ActionHero Version: `18.1.2`
- Node.js Version: `9.5.0`
- Operating System: `Windows 10`

# Steps to reproduce your error
Tested with 
```js
toRender = false
connection.pipe(tcx, { 'content-type': 'application/vnd.garmin.tcx+xml; charset=utf-8' })
```
AND
```js
toRender = false
connection.setHeader('Content-Type', 'application/vnd.garmin.tcx+xml; charset=utf-8')
connection.rawConnection.res.end(tcx)
```

Log:
```
192.168.1.2 @ 2018-02-22T18:30:55.886Z - info: [ action @ web ] to=127.0.0.1, action=mSeriesAppSession:exportFlat, params={"filename":"1000.tcx","action":"mSeriesAppSession:exportFlat","apiVersion":1}, duration=343
(node:82808) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
    at WebServer.completeResponse (D:\Keiser.Metrics.API\node_modules\actionhero\servers\web.js:371:60)
    at WebServer.emit (events.js:160:13)
    at WebServer.processAction (D:\Keiser.Metrics.API\node_modules\actionhero\classes\server.js:262:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```
---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
Can you please provide an inclusive test case that reproduces this?  I just added another test that shows in a simple case, that changing the content header with `connection.pipe` is OK: https://github.com/actionhero/actionhero/commit/6fcc60c07dc0abdb79352ce54642cbd5b9e0248c

**Comment by bayssmekanique** [comment]
Once again, this was an error on my part.  I was using destructuring assignment to pull apart the `data` object, and because `toRender` is a primitive, my `toRender` variable was just a value (_not a reference_) and thus the `data.toRender` was still set to `true`.

Would it make sense to make a setter functions on the `data` object for setting the `toRender` and `toProcess` values rather than relying on setting them directly?  I know it sounds a little overkill, but those are the only primitives on the root `data` object which would be modified, and it would prevent future issues like this.

**Comment by evantahler** [comment]
Ouch, and interesting!
It seems that if you were to make those setters/getters, that means you shouldn't destructure the API object... and to solve the /reference/ problem you had, you would also need to not destructure the API object... so either way, there's a behavior problem we need to fix first.

Perhaps we should update all the docs/examples not to do destructure?

**Comment by evantahler** [comment]
This is a great conversation for the mailing list BTW!
