### ISSUE TITLE
failed to link scoped plugins

### ISSUE THREAD

**Issue by JennyWe** [actionhero/actionhero#1185]
# Name of Issue
A directory error created by the use of the link command with scoped packages.

- ActionHero Version: `17.1.2`
- Node.js Version: `9.3.0`
- Operating System: `Microsoft Windows 10 Pro`

# Steps to reproduce your error

- Install actionhero version 17.1.2 with ` npm install actionhero@17.1.2`
- Create a new actionhero v.17.1.2 project with `npx actionhero@17.1.2 generate`
- Install with `npm install`
- Install a scoped package with `npm install @bssgmbh/ah-scope-test`
- run the link.js with  `npm run actionhero link -- --name @bssgmbh/ah-scope-test ` and I receive this error:
```
Error: ENOENT: no such file or directory, open 'C:\Users\workspace\actionHero_js\testScopeProjekt\public\plugins\@bssgmbh\ah-scope-test.link'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at Object.api.utils.createLinkfileSafely (C:\Users\workspace\actionHero_js\testScopeProjekt\node_modules\actionhero\initializers\utils.js:405:12)
    at C:\Users\workspace\actionHero_js\testScopeProjekt\node_modules\actionhero\bin\methods\link.js:50:19
    at Array.forEach (<anonymous>)
    at Object.run (C:\Users\workspace\actionHero_js\testScopeProjekt\node_modules\actionhero\bin\methods\link.js:43:7)
    at C:\Users\workspace\actionHero_js\testScopeProjekt\node_modules\actionhero\bin\actionhero:122:18
    at process.nextTick (C:\Users\workspace\actionHero_js\testScopeProjekt\node_modules\actionhero\actionhero.js:251:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)

```
# Steps to solve the error

- I modified the link.js in `\node_modules\actionhero\bin\methods`.
- I created a variable localLinkScopePath containing the scopename.  

```js
let localLinkScopePath = path.normalize(localLinkDirectory + path.sep + path.dirname(data.params.name) + path.sep)
```
- A directory is created in foreach loop 

```js
      try {
        fs.mkdirSync(localLinkScopePath);
        api.log(`${data.params.name} directory created`);
      } catch (err) {
        if (err.code == 'EEXIST'){
          api.log('The directory named `${data.params.name} exists');
        } else {
          console.log(err);
        }
      } 
```

- Now the link files are created in the scope directory. 

# still existing issue
- after  `npm start ` we cant access any of the files from the plugin
```
Localhost:8080/helloWorld.html
``` 
my question: 
- where is the problem?
- Have you any idea why accessing resources from the scoped package does not work?
I would be happy about every idea and suggestion. Thanks in advance.

**Comment by evantahler** [comment]
Are you able to upgrade to v18 of ActionHero?  here were a number of problems with `actionhero link`, and it has since been removed.  Acknowledging all the different behaviors in NPM vs YARN, and Windows vs OSX vs Linux, we've moved back to a `config/plugins.js` config file where you explicitly tell ActionHero were your plugins are.  

On OSX & NPM v5, using your plugin would look like:

```js
// from config/plugins.js
const path = require('path')

exports['default'] = {
  plugins: (api) => {
    return {
      '@bssgmbh/ah-scope-test': { path: path.join(__dirname, '..', 'node_modules', '@bssgmbh', 'ah-scope-test') }
    }
  }
}
```

With the above, your `helloWorld.html` page is visible.

**Comment by JennyWe** [comment]
Hello Evan, 
thank you for your quick reply and your solution. But unfortunately we need the ActionHero version 17.1.2. 
Have you any idea for the version 17.1.2 ? 
Thanks in advance.

**Comment by evantahler** [comment]
No, I'm sorry.  Older versions of ActionHero are no longer supported.  

In the short term, you might try making a symlink from `node_modules/@namespace/package` to `node_modules/package`, and linking the symlink rather than the true path of the name-spaced package.
