### ISSUE TITLE
Add `redis-server` or similar command to quickstart

### ISSUE THREAD

**Issue by NealHumphrey** [actionhero/actionhero#1186]
# Starting of redis-server not included in quickstart

I encountered the same issue described in this issue:
https://github.com/actionhero/actionhero/issues/1151

It appears that the conclusion from that issue was to add this note [to the documentation page here](https://www.actionherojs.com/get-started/)

"You can disable the features of ActionHero which require redis (cache, chat, tasks, etc)..."

However, the utility of that note is not understood until after trying to perform the quick start instructions and encountering the error, and then looking back at the documentation (or in my case finding the github Issue via google) to realize what was going on and that Redis could be disabled. 

# Proposed solution:
Leave the "you can disable" note, but also add a `redis-server` line to the quickstart instructions so that the quickstart demo works seamlessly the first time. Note, this is my first time using redis so I don't yet know if redis-server is indeed the correct command, but it did seem to resolve the error for me. 

- ActionHero Version: `18.1.0`
- Node.js Version: `9.6.1`
- Operating System: `OSX`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- Don't install or start the Redis server
- `npm install`
- `npm start`

Solution: 
- Run `redis-server` before `npm start`

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
Good idea!   I think in the 'requirements' section, we should add the part about ensuring that redis is always up-and-running too.  Here's the changeset: https://github.com/actionhero/www.actionherojs.com/commit/5b2bec180267d7620d0738575cb9baa1a5ef5b74

**Comment by NealHumphrey** [comment]
Perfect, looks good!
