### ISSUE TITLE
What does connection.error do?

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1199]
- ActionHero Version: `master`
- Node.js Version: `all`
- Operating System: `(OSX, Ubuntu 14, Windows 10, etc)`

`connection.error` may be an unused code path.  Can we remove it?

**Comment by Martinlck** [comment]
How do you want us to prove or not prove that is unused code path.
I'm assuming just removing it and running the tests might not be enough?

**Comment by evantahler** [comment]
Actually, I think that *would* be enough!
