### ISSUE TITLE
Not auto refresh in MacOS

### ISSUE THREAD

**Issue by kamontat** [actionhero/actionhero#1200]
# Name of Issue
Description of Issue: After I try to install `actionhero`, and I had changed some of `actions`. but the server didn't refresh itself.

- ActionHero Version: `18.1.3`
- Node.js Version: `v9.8.0`
- NPM Version: `5.7.1`
- Operating System: 
```
OS: macOS 10.13.3 17D102 x86_64
Host: MacBookPro11,4
Kernel: 17.4.0
```

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- update some text in actions folder
- **nothing refresh!! **

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
Do you have development mode enabled?  Also, the server watches *files*, not *folders*, so that means if you create a new file, you'll need to manually reload the server, but changes to existing files will be picked up.

**Comment by kamontat** [comment]
1. Already `enabled`
2. Yes, I try. But nothing refresh

**Comment by evantahler** [comment]
Can you share more information about your setup?  What shell are you using, what does your action do, etc.

We have a rigorous test that checks this functionality on OSX and Linux, which is passing. https://github.com/actionhero/actionhero/blob/master/test/core/developerMode.js

**Comment by evantahler** [comment]
ping! Any update?

**Comment by kamontat** [comment]
I didn’t do nothing, just create new project and try to change something. 

But hot reload server when config files changed, it work.

**Comment by evantahler** [comment]
I'm sorry, but I can't reproduce this problem.  I'm closing this issue.  Perhaps the folks on slack (slack.actionherojs.com) can help you?
