### ISSUE TITLE
cluster_pidfile path is not configurable

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1203]
# cluster_pidfile path is not configurable
I need to move all log and pid files to separate directories, logs is OK, but I cant move cluster_pidfile, but workers pids are moved correctly.

- ActionHero Version: `18.1.3`
- Node.js Version: `8.9.4`
- Operating System: `CentOS 7`

# Steps to reproduce your error
- Change pid path in config/api.js

**Comment by evantahler** [comment]
Great catch! 
Solved by https://github.com/actionhero/actionhero/pull/1205
