### ISSUE TITLE
unhandled rejection in cluster mode

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1225]
# unhandled rejection in cluster mode
Hi! I wrote you in previous issue, but you didn't respond and I cant reopen it. So, the problem continues, within some time instance go down processiong tasks, with message:
```
10.5.30.11 @ 2018-06-03T08:05:03.426Z - notice: cluster equilibrium state reached with 2 workers
10.5.30.11 @ 2018-06-03T08:08:02.643Z - alert: [worker #1 (26046)]: unhandled rejection => worker not found
10.5.30.11 @ 2018-06-03T08:08:02.643Z - alert: [worker #1 (26046)]:    Error: worker not found
10.5.30.11 @ 2018-06-03T08:08:02.643Z - alert: [worker #1 (26046)]:        at Queue.forceCleanWorker (/var/opt/EasyBits/NotifyService/node_modules/node-resque/lib/queue.js:250:26)
10.5.30.11 @ 2018-06-03T08:08:02.643Z - alert: [worker #1 (26046)]:        at <anonymous>
10.5.30.11 @ 2018-06-03T08:08:02.643Z - notice: cluster equilibrium state reached with 2 workers
```
So, as u can see, when worked is become resque master it goes down trying to `forceCleanWorker`.
In redis I see a lot of records in `resque:worker:app1`, in format `resque:worker:ping:app1:10034+1`. As I can understand `10034` is a process PID, but it is not exist.

As I see from `node-resque` code:
```
  async forceCleanWorker (workerName) {
    let errorPayload

    let workers = await this.workers()
    let queues = workers[workerName]
    if (!queues) { throw new Error('worker not found') }
```
So, if worker is not present in current worker list, it well be an error. OK, but why is it unhandled and workers crashes? Can you fix it?

Thank you!

- ActionHero Version: `master`
- Node.js Version: `8.11.2`
- Operating System: `CentOS 7`

**Comment by evantahler** [comment]
Note: This code is actually from the node-resque project https://github.com/taskrabbit/node-resque/blob/master/lib/queue.js#L245

I think this behavior is correct. I'll use `redis-cli` to validate.  The pid doesn't need to exist any more at the time the worked is cleaned. We are just moving things around in redis.  The goal of `foreCleanWorker` is to *save* the payload data of the stuck job, not to delete it, so you can inspect it later.  We "throw" and stop the operation when we can't accomplish the task

`workers` in this context is the hash of all workers.  We take the members of the `resque:workers` set, and take the final section after the last ":", which is the list of queues it is working on (https://github.com/taskrabbit/node-resque/blob/master/lib/queue.js#L198): 
```
127.0.0.1:6379> smembers resque:workers
1) "evantop.local:58156+1:default"
```
... which would be `workers = {'evantop.local:58156+1': 'default'}` in this case.

The reason for the explicit `throw` is that if we can't determine what "queue" the worker was working on.  We need the queue name to source the "real" name of the worker to load the failed job names.

Do you have `:` in your job names?  On one of your servers, can you please add `api.log(workers)` right before `if (!queues) { throw new Error('worker not found') }`.  That would be helpful for debugging.

**Comment by DoctorDimon** [comment]
Oh... api is not available there. Can you help me, how I can log from queue.js?

**Comment by evantahler** [comment]
oh, that's in node-resque.  You can emit perhaps, of just console.log, depending on how you are logging you actionhero application

**Comment by DoctorDimon** [comment]
```
SecureStorage @ 2018-06-03T20:31:25.839Z - info: This node is now the Resque scheduler master
workers { 'easybits-vm:1738+1': 'high',
  'easybits-vm:21825+1': 'high',
  'easybits-vm:6025+1': 'high',
  'easybits-vm:21769+1': 'high',
  'easybits-vm:21611+1': 'high',
  'easybits-vm:21520+1': 'high',
  'easybits-vm:7278+1': 'high',
  'easybits-vm:21423+1': 'high',
  'easybits-vm:21455+1': 'high',
  'easybits-vm:21703+1': 'high',
  'easybits-vm:21632+1': 'high',
  'easybits-vm:21477+1': 'high',
  'easybits-vm:20093+1': 'high',
  'easybits-vm:21769+2': 'high',
  'easybits-vm:7300+1': 'high',
  'easybits-vm:21433+1': 'high',
  'easybits-vm:21372+1': 'high',
  'easybits-vm:21835+1': 'high' }
workerName easybits-vm:21498+1
(node:7300) UnhandledPromiseRejectionWarning: Error: worker not round
    at Queue.forceCleanWorker (/var/easybits/SecureStorage/node_modules/node-resque/lib/queue.js:251:26)
    at <anonymous>
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:7300) Error: worker not round
    at Queue.forceCleanWorker (/var/easybits/SecureStorage/node_modules/node-resque/lib/queue.js:251:26)
    at <anonymous>
(node:7300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DoctorDimon** [comment]
So, as I can see, it cannot find worker with name `easybits-vm:21498+1` in workers list and crashes. As I can understand, it takes it from `resque:stat:processed` namespace, from here `resque:stat:processed:easybits-vm:21498+1`

**Comment by DoctorDimon** [comment]
Strange thing is that the key `resque:worker:easybits-vm:21498+1:high:started` actually available in redis in `resque:worker` namespace, but why it is not loaded in array of workers?

**Comment by DoctorDimon** [comment]
Any ideas?

**Comment by evantahler** [comment]
@DoctorDimon I've spent a fair amount of time trying to reproduce this, but can't.  That said, it's always best to have some code to look at!  Here's an example ActionHero project we can use

https://github.com/actionhero/test-project-slow-tasks

I've set this up so we can have an easy way to stop an ActionHero server mid-task, see that the worker is stuck, check the `:ping` keys, and watch the worker get properly cleared.  

Please try to reproduce your issue as a pull request on that new repo so we can discuss real code.

**Comment by DoctorDimon** [comment]
Great! Now Im testing my stuff...

I have analyzed the code, and have the theory - Look at https://github.com/taskrabbit/node-resque/blob/master/lib/worker.js#L290. The problem appears if record is exist in `:ping` keys and not exist in `resque:workers`.
If I have a temporary problem with redis (connection or overload), I can be a situation when worker will be removed from `resque:workers` and cannot be removed from `:ping` keys, because redis have a problem. In this case, I will see `Worker not found` error each time worker will become a resque master (this is my case).

What do you think about it?

**Comment by evantahler** [comment]
That makes sense then!  So you have a (crashed/exited) worker which only has *some* of its data in redis.  

I guess this is what we are talking about then! https://github.com/taskrabbit/node-resque/pull/247

Can you try the code in this PR, and let me know if it fixes your issue?  How do you feel about relaxing the safety of the method?

Also... you should probably get a bigger/better redis server!

**Comment by DoctorDimon** [comment]
Thanks! Im trying to test it, but I catch new Error:
```
SecureStorage @ 2018-06-12T09:48:44.165Z - alert: [worker #1 (17883)]:        at JSON.parse (<anonymous>)
SecureStorage @ 2018-06-12T09:48:44.166Z - alert: [worker #1 (17883)]:        at data.map (/var/opt/SecureStorage/node_modules/actionhero/node_modules/node-resque/lib/queue.js:310:49)
SecureStorage @ 2018-06-12T09:48:44.166Z - alert: [worker #1 (17883)]:        at Array.map (<anonymous>)
SecureStorage @ 2018-06-12T09:48:44.166Z - alert: [worker #1 (17883)]:        at Queue.failed (/var/opt/SecureStorage/node_modules/actionhero/node_modules/node-resque/lib/queue.js:310:24)
SecureStorage @ 2018-06-12T09:48:44.166Z - alert: [worker #1 (17883)]:        at <anonymous>
```
As I can see I have blank records in `resque:failed`, just row number and blank value... Dont know why...

**Comment by evantahler** [comment]
minor change pushed... one more try!  Thanks for working though this with me!

**Comment by DoctorDimon** [comment]
Updated. Waiting for results... :)

**Comment by DoctorDimon** [comment]
So, it looks like the system became absolutely stable, even with unstable connections to redis.
Great work! If If I will be in Seattle, I will buy you a beer, man! Thanx a lot! 
Hope this was the last catch )))

**Comment by evantahler** [comment]
Are you still seeing that new error, or was that a one-time thing?  That's odd because we just asked for keys the line before... we may need to do both of those reads in a transaction, or, filter out null/undefiend responses.

**Comment by evantahler** [comment]
... and I would expect the JSON.parse() to fail at that point

**Comment by evantahler** [comment]
oh! this is also solved by https://github.com/taskrabbit/node-resque/issues/250

**Comment by evantahler** [comment]
Node Resque v5.4.0 is published!
