### ISSUE TITLE
Connection is not removed from all chat rooms at destroy()

### ISSUE THREAD

**Issue by cecofreeman** [actionhero/actionhero#1257]
# Connection is not removed from the chat rooms
Description of Issue

- ActionHero Version: `^19.0.2`
- Node.js Version: `all`
- Operating System: `all`

# Steps to reproduce your error
- create several rooms
- add the connection to more than one room
- destroy the connection

---
In classes/connections.js, method destroy() , lines 152-155:
```
    if (this.canChat === true) { 
      for (let i in this.rooms) {
        let room = this.rooms[i]
        await api.chatRoom.removeMember(this.id, room)
      }
    }
```
If we have two rooms in `this.rooms` and we await for `api.chatRoom.removeMember(this.id, room)` the connection is removed from `this.rooms` and at the next iteration `i` becomes `1`, but the length of `this.rooms` is 1!

I suggest to modify the code like this:

 ```
    if (this.canChat === true) { 
      let promises = []
      for (let i in this.rooms) {
        let room = this.rooms[i]
        promises.push(api.chatRoom.removeMember(this.id, room))
      }
      await Promise.all(promises)
    }
```
Thank you

**Comment by evantahler** [comment]
Thank you! 
Would you please contribute this change in a pull request?  If you need help, you can reach the ActionHero community at https://slack.actionherojs.com

**Comment by evantahler** [comment]
solved via https://github.com/actionhero/actionhero/commit/d1960eec19f6a2129e94a8c93fca281c53337651
