### ISSUE TITLE
Regression: log is missing details

### ISSUE THREAD

**Issue by dehnhard** [actionhero/actionhero#1267]
# Name of Issue
ActionHero 19 does not print access details (for files and actions) in log like previous versions did.

- ActionHero Version: `19.0.4`
- Node.js Version: `8.11.3`
- Operating System: `Ubuntu`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- npm start
- Access something, e.g. ```http://localhost:8080/something```
- Resulting log line:
```192.168.0.61 @ 2018-11-13T09:12:57.356Z - info: [ file @ web ]```

# Expected result: as in earlier versions
- If you repeat the steps above with Actionhero version 18, the log shows:
```192.168.0.61 @ 2018-11-13T09:07:42.115Z - info: [ file @ web ] to=127.0.0.1, file={not found}, requestedFile=status, size=null, duration=null, success=false```

**Comment by evantahler** [comment]
Thank you for pointing this out!   Solved via https://github.com/actionhero/actionhero/pull/1268
