### ISSUE TITLE
Change module-reload to full server reload

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/actionhero#1275]
# Change module-reload to full server reload
This is an RFP for reworking the reload on file changes to perform a full server reload rather than reloading modules and hot-swapping.

It would also be nice to expand the "watch and reload" capability to plugins to avoid duplicating functionality in each plugin (ie: https://github.com/actionhero/ah-sequelize-plugin/blob/d0491b7f8e9e14289de5141dabd9264308f602ad/classes/sequelize.js#L63-L69)

**Comment by evantahler** [comment]
Great! This was talked about in the actionhero slack channel on 12/10/18.  There are some behaviors that the "soft" reloading of actions and tasks doesn't do as expected (like updating routes, plugins, etc).  To create the expected user behavior, a full `api.commands.restart()` could be used.

Perhaps the places that need to be changed at the specific callbacks for watchFileAndAct in actions and tasks:
* https://github.com/actionhero/actionhero/blob/master/initializers/actions.js#L99-L103
* https://github.com/actionhero/actionhero/blob/master/initializers/tasks.js#L91-L93

**Comment by evantahler** [comment]
closing via https://github.com/actionhero/actionhero/pull/1313
