### ISSUE TITLE
AH Task Tutorial Documentation

### ISSUE THREAD

**Issue by samking314** [actionhero/actionhero#1289]
# AH Task Tutorial Documentation
The AH Documentation for Tasks is not updated. Specifically, the page https://docs.actionherojs.com/tutorial-tasks.html
has an incorrect tutorial where it says that `initializers/node_schedule.js` should have in it
`initialize (api, next) {
    api.scheduledJobs = []
  }`
but this is wrong, because we're already requiring `api` from actionhero. Also, if you try running this code in your `initializers/node_schedule.js` you'll get an error saying `scheduleJobs` is undefined (because `api` is undefined because this is not the required `api`).

Instead, this documentation should say
`initialize () {
    api.scheduledJobs = []
  }`

- ActionHero Version: `19.0.4`
- Node.js Version: `10.14.1`
- Operating System: `(OSX)`

# Steps to reproduce your error
- Look at the tutorial under `initializers/node_schedule.js`

**Comment by evantahler** [comment]
Thanks for pointing this out!   Are you able to update the documentation via a pull request?

**Comment by samking314** [comment]
Sure can, Evan. Thanks for replying.

**Comment by evantahler** [comment]
Solved by https://github.com/actionhero/actionhero/pull/1290
