### ISSUE TITLE
workers parameter in cluster is ignored

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1293]
# workers parameter in cluster is ignored
workers is ignored. I tried all possible combinations but it does not work. Actually it was, but it was broken in new versions.

When i use `npm start cluster --workers=2` or `npm start cluster --workers=5`

it is always:

```
using default value of `1` for `workers`
using default value of `actionhero-worker-` for `workerTitlePrefix`
```

Other params are ignored too. It always use default value of workers depends on CPUs.

- ActionHero Version: `19.1.2`
- Node.js Version: `10.15.1`
- Operating System: `CenotOS 7`

**Comment by evantahler** [comment]
You cannot pass arguments to actionhero *though* npm that way.
* either talk to actionhero directly `./node_modules/.bin/actionhero start cluster --workers 10`
* pass the argument *around* npm `npm run actionhero start cluster -- --workers 1`

New actionhero projects no longer include `cluster` as a script for this reason
