### ISSUE TITLE
Re-enqueue the same task , after certain period , is not working

### ISSUE THREAD

**Issue by frodoe7** [actionhero/actionhero#1315]
# Re-enqueue the same task , after certain period , is not working
I have a task "AnalysisMarket"

I enqueued it to be processed ASAP and it executed well 
now there's a postProcessor middleware , which try to re-enqueue the same task again but after 1 hour

the task executed well and also executed the postProcessor function well ,
but it did not ran the task again after 1 hour

here's the code

`await api.tasks.enqueueIn(ms(data.period),"AnalysisMarket", {exchange : data.exchange , hash : data.hash} , 'default'); // I am not sure if this code passed well or not`

the first parameter ms(data.period) hold 3600000 (which equals 1 hour)

- ActionHero Version: `19.1.4`
- Node.js Version: `v10.15.1`
- Operating System: `MAC High Sierra`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- create an action which enqueue a task "X" to be executed ASAP
`await api.tasks.enqueue("X", {data: 'data'}, 'default')
`
- create the task with `this.name = "X" and run function`
- create initializer to declare a middleware for the task with postProcessor function
- inside postProcessor , try to enqueue task "X" after certain period

`await api.tasks.enqueueIn(1000000,"AnalysisMarket", {exchange : data.exchange , hash : data.hash} , 'default');`

**Comment by evantahler** [comment]
You are discussing a lots of features of a robust project.  If your could provide a sample project, that would be helpful.

Just a guess, perhaps you are running into this issue? https://github.com/taskrabbit/node-resque/issues/284 . To test for it, every time you enqueue the job, check for an error

**Comment by frodoe7** [comment]
> You are discussing a lots of features of a robust project. If your could provide a sample project, that would be helpful.
> 
> Just a guess, perhaps you are running into this issue? [taskrabbit/node-resque#284](https://github.com/taskrabbit/node-resque/issues/284) . To test for it, every time you enqueue the job, check for an error

This is not logical , the task should be already finished 1 hour ago , as the duplicate one ran after 1 hour

however there's a good point here in case it's still running , how to manually stop the current task (mark it as finished)?
so when re-enqueue it , it should be new not duplicate

**Comment by frodoe7** [comment]
Hi @evantahler ,

I built a minimal project to illustrate the issue : please check it [here](https://github.com/frodoe7/ActionHeroIssue)
it is the default Actionhero template which generated from : npx actionhero generate
with 3 added files

taskX.js file in tasks folder
which includes : 

```
const {api, Task} = require('actionhero')

module.exports = class taskX extends Task {
  constructor () {
    super()
    this.name = 'taskX'
    this.description = 'I do any random job'
    this.middleware = ['taskXpostProcess']
  }

  async run (data) {
    console.log(data.x);
    return true;
  }
}
```

iniTasks.js in initializers folder
which includes :

```
const {Initializer, api} = require('actionhero')

module.exports = class iniTasks extends Initializer {
  constructor () {
    super()
    this.name = 'iniTasks'
  }

  async start() {
    await api.tasks.enqueue("taskX", {x: 'taskX enqueued'}, 'default')
  }
}
```

iniMiddleware.js in initializers folder
which includes :

```
const {api, Initializer} = require('actionhero')

module.exports = class taskMiddleware extends Initializer {
  constructor () {
    super()
    this.name = 'taskMiddleware'
  }

  async initialize() {
    const middleware = {
        name: 'taskXpostProcess',
        postProcessor: async function () {
            console.log("try enqueue the task after 5 seconds");
            await api.tasks.enqueueIn(5000 , "taskX", {x: 'taskX enqueued'}, 'default')
          }
    }

    api.tasks.addMiddleware(middleware)
  }
}
```

it logs 
> "try enqueue the task after 5 seconds"

but the below line does not work - it does not enqueue it
`await api.tasks.enqueueIn(5000 , "taskX", {x: 'taskX enqueued'}, 'default')`
however the below one will work and will enter to infinite loop
`await api.tasks.enqueueIn("taskX", {x: 'taskX enqueued'}, 'default')`

**Comment by frodoe7** [comment]
I detected the issue , delayedIn function is not working at all , it does not execute the task after the period , I think it's related to [this issue ](https://github.com/actionhero/actionhero/issues/1156)
but author closed it , without illustrating the issue reason
 #1156

**Comment by frodoe7** [comment]
It was my fault , I missed to change the scheduler to true
