### ISSUE TITLE
Can't upload file from client to my Actionhero app

### ISSUE THREAD

**Issue by frodoe7** [actionhero/actionhero#1323]
# Name of Issue
I tried to manually use multer , but it did not work well
looks like - I have to use the built-in uploading function inside Actionhero

however I read the docs here [Uploading Files](https://docs.actionherojs.com/tutorial-web-server.html)

yes , I log the result in success , but it actually not save the file in my folders

```
// what the params look like to an action
{ action: 'uploader',
  file1:
   { domain: null,
     _events: null,
     _maxListeners: 10,
     size: 5477608,
     path: '/app/actionhero/tmp/86b2aa018a9785e20b3f6cea95babcca',
     name: '1-02 Concentration Enhancing Menu Initialiser.mp3',
     type: 'audio/mp3',
     hash: false,
     lastModifiedDate: Wed Feb 13 2013 20:32:49 GMT-0800 (PST),
     _writeStream:
      { ... },
     length: [Getter],
     filename: [Getter],
     mime: [Getter] },
  file2:
   { domain: null,
     _events: null,
     _maxListeners: 10,
     size: 10439802,
     path: '/app/actionhero/tmp/6052010f1d75ceaeb9197a9a759124dc',
     name: '1-10 There She Is.mp3',
     type: 'audio/mp3',
     hash: false,
     lastModifiedDate: Wed Feb 13 2013 20:32:49 GMT-0800 (PST),
     _writeStream:
      { ... },
  key1: '123',
  key2: '456',
 }
```

- ActionHero Version: `19.1.4`
- Node.js Version: `v10.15.1`
- Operating System: `OSX`

I only need to be able to upload a file, and using Multer is better for me

**Comment by frodoe7** [comment]
@evantahler I managed to solve it , you can completely delete this issue

**Comment by evantahler** [comment]
I’m happy to hear you’ve solved it!

Can you share what you did in case others have the same issue?

**Comment by frodoe7** [comment]
@evantahler , I just found Actionhero handle the uploading process by default
so I just don't need to do any extra step
