### ISSUE TITLE
how to send message to all clients from the server side update loop?

### ISSUE THREAD

**Issue by Cariaga** [actionhero/actionhero#1369]
server side Game loop? or should i call an Action keep calling an action to get updates?
if i wanted continuous update i do this on the client but that would be bad is it possible in the server  update loop their instead?
```
  setInterval(function(){
          client.action('updateloop', { name: 'updateloop' }, function (NewUpdates) {
            
          });
        }, 500);
``
or maybe i should run actionhero-node-client on server that will act as a gameloop?

**Comment by evantahler** [comment]
A few notes: 

* Do not call actions from actions. That’s more of an anti-pattern in actionhero. Any “sharable” code should exist in Initializers, and Actions would call those Initializers. General practice is “thin actions, fat initializers”. All the good logic will go in Initializers and the Actions just coordinate/control what is needed.
* If you only have one API server, this will work, but if your cluster expands to more than one server, you'll be double/tripple publishing.  Perhaps investigate the `task` system for this publication, or if you need something faster (sub-second) you can look into checking which node is currently the resque master, and only running the interval on that server .

Either way, you can likely use `api.chatRoom.publish()` to reach all clients in your room
