### ISSUE TITLE
Not all exported functions may be an initialiser 

### ISSUE THREAD

**Issue by inian** [actionhero/actionhero#1377]
# Name of Issue  

[This line](https://github.com/actionhero/actionhero/blob/899b645d68682ec623296fefc587b2c5b641cc98/src/classes/process.ts#L143) assumes that any function exported from an file inside the initialiser folder is an initialiser. And when [validate](https://github.com/actionhero/actionhero/blob/899b645d68682ec623296fefc587b2c5b641cc98/src/classes/process.ts#L152) is called on that. But there might be other functions that I might be exporting from an Initialiser file (utility functions etc). I think that the class should check if it extends from Initialiser class first before calling .validate etc or should it only check the default exports. 

- ActionHero Version: `21.x.x`

# Steps to reproduce your error
Create a initialiser which exports a normal JS function and an initialiser class. 

```
export function foo() {}
export class User extends Initializer {}
```

**Comment by evantahler** [comment]
@gcoonrod what do you think about this?  Should we continue assuming that every export in a file in initializers is a descendant of `Initializer`?  This isn't a new problem with typescript... but it has becomes more obvious. 

The same is likely true for files in `/actions`, `/tasks` and `/servers` as well as `/initializers`

**Comment by evantahler** [comment]
I'm thinking that this would be a good thing to do... even if we don't recommend it.   So we would check for `exportedClass instanceof Initializer` (etc) in each of the loaders.

@inian - is this something you would like to work on?

**Comment by inian** [comment]
Previously we just looked at the default export ([link](https://github.com/actionhero/actionhero/blob/7005e4f0c3e9d21aa64b3ddb4510c217b21891d9/classes/process.js#L108)) but now we loop through all the export keys ([link](https://github.com/actionhero/actionhero/blob/899b645d68682ec623296fefc587b2c5b641cc98/src/classes/process.ts#L141)). 

Should we just look at the default export instead to match the behaviour with the older version? In this case the documentation needs to be changed to `export default class Users extends Initializer` instead. 

Or I can we can check all the exports like we do right now and I can add a check to see if they are really Initializers.

**Comment by evantahler** [comment]
Ah!  For a while we've allowed multiple exports from [action](https://github.com/actionhero/actionhero-tutorial/blob/master/actions/blog.js) and task files, but it looks like this is the first time we've checked it for initializers.   

I think as a principal it would be best not to treat the `default` export as anything special... and to always check all exports from a file, regardless of if they named `default` or `myInitialer`... which would imply we should add a type check (`instanceof` perhaps)

**Comment by evantahler** [comment]
Hi @inian! Any progress?

**Comment by evantahler** [comment]
Hello again @inian! Do you need any help?

**Comment by inian** [comment]
Hey Evan, I will follow up with a PR this weekend!
