### ISSUE TITLE
Unable to start actionhero in cluster mode

### ISSUE THREAD

**Issue by inian** [actionhero/actionhero#1387]
# Name of Issue
Description of Issue

Running
./node_modules/.bin/actionhero start cluster --daemon gives a ENOENT error.

- ActionHero Version: `21.x`
- Node.js Version: `12.x`
- Operating System: `(Ubuntu)`

Changing [this line](https://github.com/actionhero/actionhero/blob/0ddca3621dd18bace535ec6efa3a7b76186fec70/src/bin/actionhero.ts#L188) to the following fixes this issue

```
const command = path.normalize(actionheroRoot + "/bin/actionhero.js");
```
 
If this fix looks okay, i can send a PR

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by evantahler** [comment]
The extension was purposely left off so that both `.ts` and `.js` files will match.  

The following steps work for me to generate a new project and start it in cluster mode:

```bash
cd test # an empty directory
npx actionhero generate
npm install
./node_modules/.bin/actionhero start cluster
```

Can you try the same and let me know if it works?  I wonder if this is difference is how node modules are resolved between *nix and OSX...

**Comment by evantahler** [comment]
I tried it in an ubuntu docker image as well:

```
docker run --expose 8080 -ti ubuntu /bin/bash
```

```bash
# now in the docker image
apt-get update && apt-get upgrade

# install NVM
apt-get install curl -y
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
source ~/.bashrc

# install node and set it up to run as root (we are in docker... it's fine)
nvm install 12
npm config set user 0 && npm config set unsafe-perm true

# install & start redis
apt-get install redis-server -y
redis-server --daemonize yes

# test in an empty directory
mkdir /tmp/test && cd /tmp/test 
npx actionhero generate
npm install
./node_modules/.bin/actionhero start cluster
```

**Comment by evantahler** [comment]
... and after all that I missed that you were using the `--daemon ` flag.  

I was actually considering moving that entirely... can you share more about what you are using it for?  How are you deploying Actionhero?

**Comment by inian** [comment]
Just as a simple way to run actionhero as a daemon and restart it. It is a relatively small application, so just running actionhero behind nginx and starting actionhero as a daemon

**Comment by evantahler** [comment]
Makes sense!

Would using a tool like [PM2](https://pm2.keymetrics.io/) or your OS's background process manager (ie [`systemd`](https://tibbo.com/linux/nodejs/service-file.html)) be a detriment if this were to be removed?

**Comment by inian** [comment]
Shouldn't be -  I switched to pm2 in the last 2 days and it has been running without any issues since.

**Comment by evantahler** [comment]
Ok... I'll remove it then! 
Thanks!

**Comment by evantahler** [comment]
removed `--daemon` option in https://github.com/actionhero/actionhero/pull/1388
