### ISSUE TITLE
generate action CLI not working

### ISSUE THREAD

**Issue by Il9** [actionhero/actionhero#1394]
# generate action CLI not working
run generate action CLI then `handleUnbuiltProject` function is not running
file in `bin > actionhero.ts`
["generate", "action"] not included in if process `line:186 ~`
How to use it?
And new create CLI same problem

```js
const argsMatch = (a, b) => {
        if (a.length !== b.length) {
            return false;
        }
        for (const i in a) {
            if (a[i] !== b[i]) {
                return false;
            }
        }
        return true;
    };
    if (argsMatch(commands, ["version"])) {
        handleUnbuiltProject(commands);
    }
    else if (argsMatch(commands, ["generate"])) {
        handleUnbuiltProject(commands);
    }
// =============here=============
    else if (argsMatch(commands, ["generate", "plugin"])) {
        handleUnbuiltProject(commands);
    }
    else {
        handleMethod(commands);
    }
```

- ActionHero Version: `21.0.9`
- Node.js Version: `10.16.0`
- Operating System: `OSX`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- Make a new Action with `npx actionhero generate action --name=myAction`

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community.  We can help!

**Comment by Il9** [comment]
my mistake

**Comment by evantahler** [comment]
cool, good luck!
