### ISSUE TITLE
How can you load environment variables from an API and set them into config?

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1421]
From Romil Shah on Slack

> I am not trying to set the process.env as it's not compatible as per case. My setting variables are in form of JSON object along with nested too so It will not make sense to set in process.env as that will be similar to just key/value pair as flat level.

> So I am trying to fetch the setting values from an api and setting it into a singleton constant object which can be accessible into various config files such as api.ts, sequelize.ts etc. With the previous version of actionhero this was working for me as I was loading the setting values with async request in boot.js but after upgration, with server.ts this is not working for me.

> Because, all the config files are loaded first before server.ts, so I cannot set the singleton object from server.ts

What's the process to do something async in `server.ts, set a process.env variable before the config is initialized?

**Comment by evantahler** [comment]
Here's an example to show how this works:  Assuming your config files still want to reference something in `process.env`, you can write to `process.env` before starting the Actionhero process.  Any modifications to your env will then be available to the config system at that time.

File: `src/server.ts`
```ts
import { Process } from "./index";

// load any custom code, configure the env, as needed
async function loadAsyncConfig() {
  await new Promise(resolve => {
    console.log("getting remote config...");
    setTimeout(resolve, 1000);
  });

  process.env.PORT = "1234";
}

async function main() {
  await loadAsyncConfig();

  // create a new actionhero process
  const app = new Process();

  // handle unix signals and uncaught exceptions & rejections
  app.registerProcessSignals();

  // start the app!
  // you can pass custom configuration to the process as needed
  await app.start();
}

main();
```

**Comment by inian** [comment]
Hey Evan, 

This is the set up I am trying to fix

src/config/api.ts
```js
import { secrets } from "../lib/secrets";
console.log("importing secrets", secrets);
// use secrets to populate config
```

src/lib/secrets.ts
```js
// singleton secrets object
// will have the secrets loaded to the correct value after loadSecrets function has been called
export const secrets = {};
export async function loadSecrets() {
  // load async config
  secrets = asyncConfig
}
```

server.ts
```js
async function loadAsyncConfig() {
  console.log("async load");
  // load config in async way
}

async function main() {
  console.log("main");
  await loadAsyncConfig();

  // create a new actionhero process
  const app = new Process();

  // handle unix signals and uncaught exceptions & rejections
  app.registerProcessSignals();

  // start the app!
  // you can pass custom configuration to the process as needed
  await app.start();
}
```

When I run this, I get the following output
```
importing secrets {}
main
in load async
start
```

The main problem is the server.ts is run *after* secrets are being imported and calling `loadAsyncConfig` inside `main` doesn't help because it is too late by then since the configuration files are using `{}` as the secret. 

Prior to v23, using boot.js worked because boot.js was called *before* the config files were imported. And calling `loadAsyncConfig` had the secrets ready for the config files to use. 

What is the equivalent way to run some async code before the config/*.ts files are loaded in the latest version?

**Comment by crrobinson14** [comment]
@evantahler How hard would it be to make config blocks async functions? IE if when loading the block, check to see if it's a function instead of an object, and if so async-call it and use its result as the config?

**Comment by evantahler** [comment]
@crrobinson14 that's a good suggestion!  This is getting into the territory of "top level await", which is currently in the "proposal" stage for the next version of ECMAScript (JS).   

Here are some docs on the pro/cons of it... along with some hacks! 
* https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221
* https://github.com/tc39/proposal-top-level-await

I'll take a crack at it!

**Comment by evantahler** [comment]
I believe that the best way to accomplish this would be not to export a static config object from actionhero, but rather an async config getter, ie: 

```ts
import { getConfig } from 'actionhero'

async myModule () {
  const config = await getConfig();
}
```

**Comment by evantahler** [comment]
@inian I think that I'm confused by your example.  You are loading `secrets` from your config file, which means it will be loaded as soon as the first actionhero file (any of them) are required, long before your `main` function is run.  

If secrets just set `process.env` it would work.

**Comment by inian** [comment]
Hey Evan, this approach worked with v21 since boot.js was invoked before everything else and that was a good place to load async configuration. As you mentioned, now `main` function is run after config is loaded which makes it impossible to load configuration in an async way from v22.

I am a bit uneasy using process.env for my secrets and we have nested objects for our secrets which makes using process.env variables not clean.

**Comment by evantahler** [comment]
Here's an example project that shows how to modify `process.env` via an async function before importing Actionhero https://github.com/actionhero/example-with-custom-env

**Comment by evantahler** [comment]
In https://github.com/actionhero/actionhero/pull/1511, I've changed the default import statement of Actionhero within `server.ts` to make it simpler to modify the env.
