### ISSUE TITLE
Websocket Client Documentation

### ISSUE THREAD

**Issue by fairhat** [actionhero/actionhero#1436]
Hello, I couldn't find any documentation on how to use the generated websocket client except for:
https://www.actionherojs.com/tutorials/websocket-server

Also in the above example client.action has a callback with 2 params
`
client.action("someaction", {}, function (error, data) {
 // some logic
})
`
however, testing it on my server has only 1 param on callback (the first one) which always contains a response object with either my response or an error property (from actionhero)

Is this wanted?
Does a documentation page (API docs, not tutorial/demo) for the Socket client exist?

Actionhero Version: 22.0.6
Node version: v12.16.1

**Comment by evantahler** [comment]
Yep, the tutorial is the best starting point.  In Actionhero, once your client is connected, you can use the rest of the system (actions, chat, etc) in the same way as the HTTP clients.  Is there something specific you are looking for?  There's also a [demo chat page](https://github.com/actionhero/actionhero/blob/master/public/chat.html) that should be generated with a new project 

I'll update the docs to indicate that there is indeed only one argument to the `action` callback. Thanks @fairhat!

**Comment by fairhat** [comment]
No, nothing specific. But since it is part of the framework, a separate docs page would be nice to see the specification.
Also Promises support (to be able to use async await) would be very nice. Could help in a PR with that

Something like: https://docs.actionherojs.com/modules/chatroom.html but for the clientside part
There is just a reference to Primus and i was searching on primus for e.g "roomAdd", "action".

**Comment by evantahler** [comment]
Please send in a pull request with any updates to the tutorials you think would be helpful!  All those pages are markdown, and can be found here: https://github.com/actionhero/www.actionherojs.com/tree/master/tutorials I'm happy to help if you have any questions about working on the www site.  docs.actionherojs.com is actually built from the typescript definitions automatically, but the client-side library is written in [javascript at the moment](https://github.com/actionhero/actionhero/blob/master/client/ActionheroWebsocketClient.js).  I think the path forward would be converting that to TS and making compilation of it part of the normal Actionhero build process and then the docs could be generated as well! 

Updating the http/websocket client library to have options for both async/await and callbacks in a way that browsers are happy with (without needing a transpiler like babel) would be awesome!
