### ISSUE TITLE
how Actionhero tests its own servers?

### ISSUE THREAD

**Issue by skpandey1294** [actionhero/actionhero#1438]
how Actionhero tests its own servers?

_Originally posted by @skpandey1294 in https://github.com/actionhero/actionhero/issues/268#issuecomment-610744320_

**Comment by evantahler** [comment]
Hi @skpandey1294! We've got a whole portion of our test suite (which uses Jest) dedicated to each server - https://github.com/actionhero/actionhero/tree/master/__tests__/servers/web

**Comment by evantahler** [comment]
If you want to learn more about the internals of Actionhero, join us on Slack - https://slack.actionherojs.com
