### ISSUE TITLE
Change logAction logic

### ISSUE THREAD

**Issue by witem** [actionhero/actionhero#1504]
**Is your feature request related to a problem? Please describe.**

In our application we use `AppError(`as instance of `Error` with some additional fields). For send correct error to API users we parse error in `config/errors.js` based on type of Error. If `AppError `we add correct message and code, as example `AppError`: "Transaction already refunded". And if it is generic Error we return "Internal error". We start migrate to 22 version. And have some problem. When we throw `AppError` in our app it's logs by Actionhero as Error, and splits stack to different lines, what good for console, but not good to elasticsearch as logs storage(`winston-elastic`). Before we resolve this problem by redefine `api.log` method but now, with 22 version of Actionhero it's not possible.

For me this issue contain two problems:
* logging stack trace by separate `log` calls. After search in Actionhero project I find 2 places that have similar logic([actionProcessor](https://github.com/actionhero/actionhero/blob/master/src/classes/actionProcessor.ts#L146), [exceptions](https://github.com/actionhero/actionhero/blob/master/src/initializers/exceptions.ts#L95-L102))
* logging our internal AppError with `severity: error`. Best for us, it not logs action error if it matches some pattern. But for Actionhero maybe be simple add possibility to redefine log module

**Describe the solution you'd like**
* Not log every stack trace line by separate `log` call
* Add possibility to redefine `log` function or add some filtration function(or formatting with filtration possibility)

If we reach an agreement how to resolve this in the best way, I can do PR.

**Comment by evantahler** [comment]
@witem check out https://github.com/actionhero/actionhero/pull/1505 which moves all the logs to a single line

Regarding a custom logger, can you share more about what you are doing?  We also added support for rendering custom properties on the Error, like `error.code`

```ts
import { api, Action } from "./../index";

class AuthenticationError extends Error {
  code: string;

  constructor(message, code = "AUTHENTICATION_ERROR") {
    super(message);
    this.code = code;
  }
}

export class ValidationTest extends Action {
  constructor() {
    super();
    this.name = "broken";
    this.description = "I am broken";
    this.inputs = {};
    this.outputExample = {};
  }

  async run({ params, response }) {
    throw new AuthenticationError(`broken`);
  }
}

```

**Comment by witem** [comment]
#1505 resolve major issue. 

About custom logger. We use two type of errors `AppError` and `Error`, and  `AppError` is user oriented error. And better for application logs if we not log `AppError`-s to stderr, because it's normal app state, it's main reason. 
Also in some case, we use redefined `log` function for get additional metrics, but it can be done in different ways.
I think the best way it's add some filtering function to `log` method. And by default filtering function always return true. But it can be extended in config

**Comment by witem** [comment]
@evantahler thanks for fix. When you can release this changes?

**Comment by evantahler** [comment]
This weekend!

**Comment by evantahler** [comment]
And... it's deployed :D
