### ISSUE TITLE
Typo in the Actions tutorial

### ISSUE THREAD

**Issue by darer** [actionhero/actionhero#1536]
Typo in the Actions tutorial

The following line of code does not work because "webSocket" should actually be "websocket" (all lowercase):
`this.blockedConnectionTypes = ['webSocket']`
URL of the Actions tutorial where I found the typo: https://www.actionherojs.com/tutorials/actions

- Actionhero Version: `23.0.4`
- Node.js Version: `14.4.0`
- Operating System: `Ubuntu 20.04 LTS`

# Steps to reproduce:
Just add the above line to any action and test it.

**Comment by evantahler** [comment]
Thank you! 

Corrected in https://github.com/actionhero/www.actionherojs.com/commit/3dc04fee93b36070de6483cb22fd9672a11e1c6c
