### ISSUE TITLE
How to run Actionhero with windowServices?

### ISSUE THREAD

**Issue by thiemdp** [actionhero/actionhero#1564]
Hi!
i'm using command: "startprocl": "set NODE_ENV=production && npx actionhero start cluster" run in cmd.
now, i want run in windowservices.
How to run Actionhero with windowServices?
thanks.

**Comment by evantahler** [comment]
FYI  - Newer versions of Actionhero do not use `actionhero start cluster`.  we now run `node server.js` directly, where server.js/ts is in your project

**Comment by evantahler** [comment]
Closing this issue due to lack of response
