### ISSUE TITLE
Docs About Routes outdated

### ISSUE THREAD

**Issue by martnst** [actionhero/actionhero#1582]
# Name of Issue

Description of Issue

- Actionhero Version: `23.0.5`

On the [tutorial site](https://www.actionherojs.com/tutorials/web-server#Routes) are code examples with exporting a `function` whereas the current version is exporting an object. 

```
export const DEFAULT = function(api) {
  return {
    /* … */ 
  };
}
```

vs 

```
export const DEFAULT = {
  routes: (config) => {
    return {
      /* … */ 
    };
  },
};

```

**Comment by evantahler** [comment]
Thanks for pointing this out!
