### ISSUE TITLE
simple console.log periodic task creates exceptions

### ISSUE THREAD

**Issue by yiwei138** [actionhero/actionhero#1636]
# simple console.log periodic task creates exceptions

Description of Issue

- Actionhero Version: `24.0.1`
- Node.js Version: `14.15.0`
- Operating System: `Windows 10`

# Steps to reproduce your error

- Make a new actionhero task with `actionhero generate task --name=ClockTask`
- Edit with the following code:
```
export class ClockTask extends Task {
  constructor() {
    super();
    this.name = "ClockTask";
    this.description = "I say hello";
    this.frequency = 1000;
    this.queue = "low";
  }

  async run() {
    console.log("task running");
  }
}
```
- Enable scheduler and set minTaskProcessors and maxTaskProcessors
```
scheduler: true,
minTaskProcessors: 1,
maxTaskProcessors: 99,
```
- Generates error below at intervals when server start
```
error: error from task name=task:this.connection.redis.popAndStoreJob is not a function queue=low worker=1 stacktrace=TypeError: this.connection.redis.popAndStoreJob is not a function
```
- Note: I did not create any servers under `servers` folder

**Comment by evantahler** [comment]
Huh! I can't reproduce this (OSX), and we test this kind of thing in the test suite (Ubuntu).

```
# In a new directory
npx actionhero generate
npm install
npx actionhero generate task --name clockTask --queue low --frequency 1000
# update the settings in `/config/tasks.ts`
npm run dev
npm start
```

Can you share a whole project that reproduces this?  Perhaps you have a globally-installed (older?) version of actionhero that you are inadvertantly using?

**Comment by yiwei138** [comment]
> Huh! I can't reproduce this (OSX), and we test this kind of thing in the test suite (Ubuntu).
> 
> ```
> # In a new directory
> npx actionhero generate
> npm install
> npx actionhero generate task --name clockTask --queue low --frequency 1000
> # update the settings in `/config/tasks.ts`
> npm run dev
> npm start
> ```
> 
> Can you share a whole project that reproduces this? Perhaps you have a globally-installed (older?) version of actionhero that you are inadvertantly using?

Thanks for the help, I have figured out the causing error.
-  `node-resque/dist/core/connection.js`
```
loadLua() {
        const luaDir = path.join(__dirname, "..", "..", "lua");
        const files = fs.readdirSync(luaDir);
        for (const i in files) {
            const file = files[i];
            const { name } = path.parse(file);
            const contents = fs.readFileSync(path.join(luaDir, file)).toString();
            const lines = contents.split('\n');  <===== The error is gone when I change to '\n' instead of os.EOL
            const encodedMetadata = lines[0].replace(/^-- /, "");
            const metadata = JSON.parse(encodedMetadata);
            this.redis.defineCommand(name, {
                numberOfKeys: metadata.numberOfKeys,
                lua: contents,
            });
        }
    }
```
- It seems that the lines are not split correctly when using os.EOL, I'm not sure is it my com specifically or its Win10 prob

**Comment by evantahler** [comment]
That's a big deal! Cam you open the issue in the Actionhero/node-resque project?

**Comment by yiwei138** [comment]
> That's a big deal! Can you open the issue in the Actionhero/node-resque project?

Sure, heres the link:
[https://github.com/actionhero/node-resque/issues/465](url)

**Comment by yiwei138** [comment]
> That's a big deal! Can you open the issue in the Actionhero/node-resque project?

Also I am new to actionhero, jist curious is there a way to send broadcast to specific connection in a room? 👎

**Comment by evantahler** [comment]
Sure! Check out `chatRoom.broadcast`
https://docs.actionherojs.com/modules/chatroom.html#broadcast

**Comment by yiwei138** [comment]
> Sure! Check out `chatRoom.broadcast`
> https://docs.actionherojs.com/modules/chatroom.html#broadcast

but isn't that sending to `all` connection? I wish to send to one connection only.

**Comment by yiwei138** [comment]
> > Sure! Check out `chatRoom.broadcast`
> > https://docs.actionherojs.com/modules/chatroom.html#broadcast
> 
> but isn't that sending to `all` connection? I wish to send to one connection in that room only.

I have found out that using server websocket.sendMessage could achive this, thanks! :)

**Comment by evantahler** [comment]
The `broadcast` command does require that you provide a room. Only the connections in that room will get your message.

**Comment by yiwei138** [comment]
> The `broadcast` command does require that you provide a room. Only the connections in that room will get your message.

Sorry this might seems a simple question, but how do I connect to my newly created websocket server from client? Is it by setting the apiPath in client.options? It always connect to the default websocket server :)

**Comment by evantahler** [comment]
Join us in [slack](https://slack.Actionhero js.com)! There are more people to help there.
