### ISSUE TITLE
State not changed to connected on reconnecting

### ISSUE THREAD

**Issue by SpeedyC86** [actionhero/actionhero#1638]
https://github.com/actionhero/actionhero/blob/35240aa857c0a06d8415e289eeacd9dec76a4ef0/client/ActionheroWebsocketClient.js#L66

self.state = 'connected'
on reconnect the state is not put back to connected and all the actions after reconnect are sent using http.

**Comment by evantahler** [comment]
Do you think this would be the right behavior? https://github.com/actionhero/actionhero/pull/1639

**Comment by SpeedyC86** [comment]
That is how I've fixed it outside in the event handler to make it work.

**Comment by evantahler** [comment]
closed by #1639
