### ISSUE TITLE
Hotreload in Docker

### ISSUE THREAD

**Issue by andramazo** [actionhero/actionhero#1662]
I am developing my API service using actionhero inside Docker container. I am debugging the application using following command:

 `ts-node-dev --transpile-only --inspect=0.0.0.0 -- ./node_modules/.bin/actionhero start`

Hot reloading is not working inside Docker container.
actionhero version : 21.0.9

Is there any way to hot reloading?

**Comment by evantahler** [comment]
Looking back at `v21.0.9` it looks like the recommended way to run "dev" mod would have been:  `ts-node-dev --no-deps --transpile-only ./node_modules/.bin/actionhero start`.  Note the lack of `--` from your command


(from https://github.com/actionhero/actionhero/blob/v21.0.9/templates/package.json.template#L27)

**Comment by evantahler** [comment]
Closing due to lack of comment
