### ISSUE TITLE
Action Template property doesn't work well

### ISSUE THREAD

**Issue by krlicmuhamed** [actionhero/actionhero#1693]
How do I declare a Action Template variable authenticate in my example.
```
export default class Status extends Action {
  constructor() {
    super();
    this.name = "status";
    this.description = "I will return some basic information about the API";
    this.outputExample = {
      id: "192.168.2.11",
      actionheroVersion: "9.4.1",
      uptime: 10469,
    };
    this.authenticate = true; // throws an error even though It is defined in an initializer
    // throws (src/actions/status.ts:26:10 - error TS2339: Property 'authenticate' does not exist on type 'Status'.)
  }
```
Initializer middleware code contains data.actionTemplate.authenticate ie.
```
        // Middleware code
        if (data.actionTemplate.authenticate && api.jwtauth.enabled[data.connection.type]) {
          tokenRequired = true;
        }
```
This is a reproduction of the error in a project https://github.com/krlicmuhamed/apiauth 
I get `stacktrace=Error: name is required for this action`
Thanks

**Comment by evantahler** [comment]
It looks like you are still trying to extend `Action`, not a new class with the new properties you want to add `this.authenticate`.  There's an example @ https://www.actionherojs.com/tutorials/actions - Extending the Action Class
