### ISSUE TITLE
Starting app in docker container without "tls: {}" prop in redis config

### ISSUE THREAD

**Issue by maxLogvynyuk** [actionhero/actionhero#1786]
Actionhero Version: 25.0.4
Node.js Version: 14.16.0
Operating System: (Linux Mint 20)
repo - https://github.com/maxLogvynyuk/actionhero-boilerplate
branch dev/streams
docker-image - node:14-alpine
redis - amazon 

Problem:
When you don`t set "tls: {}" prop in redis config application not start and not give errors in docker container (node:14-alpine)

**Describe the solution you'd like**
I think need to add some error handling or log notification because for now app like frozen in starting step and not show any errors and not closing.

**Describe alternatives you've considered**

**Additional context**

**Comment by evantahler** [comment]
Sorry for the delay!

Can you confirm if your redis configuration is using redis + SSL (usually enabled on redis v6)
