### ISSUE TITLE
memberDetails are blank when getting stored in Redis

### ISSUE THREAD

**Issue by thechewu** [actionhero/actionhero#1958]
# Name of Issue
memberDetails are blank when getting stored in redis

Description of Issue
Member details do not get stored properly since generateMemberDetails does not get awaited in addMember, and the promise itself is stringified, which results in a blank object.

This is the line that should be awaited: https://github.com/actionhero/actionhero/blob/main/src/modules/chatRoom.ts#L246

- Actionhero Version: `x.x.x` (look in your package.json)
- Node.js Version: `x.x.x` (`node --version`)
- NPM (or yarn) version: `x.x.x` (`npm --version`)
- Operating System: `(OSX, Ubuntu 14, Windows 10, etc)`

# Steps to reproduce your error

- Make a new actionhero project with `npx actionhero generate`
- Run `npm install`
- Join the example chat room and observe results through redis inspector

*Note: That without a way to reproduce your issue, we probably will be unable to help you and the issue will be closed.*

## Logs or Test that confirm the issue
Screenshot from redis-commander of default records, and then a record after the await was added:
![image](https://user-images.githubusercontent.com/3494518/133965280-dc62997e-36ce-4476-9f0d-680adf507343.png)

---

If your "issue" does not fit into this template, it might not be an issue! Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community. We can help!

**Comment by evantahler** [comment]
Thank you for finding this bug! It will be fixed by https://github.com/actionhero/actionhero/pull/1964
