### ISSUE TITLE
[Feature]: Swagger in-path variable replacement only works for 5 path parts deep

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#2038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Check out  https://github.com/actionhero/actionhero/blob/85faefc30c61ae9dc931b02d5c4d0c0ede86c235/src/actions/swagger.ts#L80-L86

We are only replacing the variable definitions in paths like `/api/:thing/path/:stuff` up to 5 path-parts deep.  This is because we want to capture the matched string (`$1`) and use it as the replacement value.  

We can do better:
* Fancier RegExp?
* A loop?

### Describe the solution you'd like.

We can traverse all the path parts can capture/replace all the in-URL variables

**Comment by evantahler** [comment]
cc @pedroslopez

**Comment by pedroslopez** [comment]
I believe this works out fine if you use the global flag on the regex e.g. 
```js 
path.replace(/\/:(\w*)/g, "/{$1}") 
```

Demo on node shell:
```
Welcome to Node.js v15.14.0.
Type ".help" for more information.
> const path = "/api/:thing/path/:stuff/:more/:vars/go/:here"
undefined
> path.replace(/\/:(\w*)/g, "/{$1}") 
'/api/{thing}/path/{stuff}/{more}/{vars}/go/{here}'
```
