### ISSUE TITLE
[Bug]: actionhero generate does nothing on windows

### ISSUE THREAD

**Issue by YamCrack** [actionhero/actionhero#2275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i run command 

npx actionhero generate

nothing happens.

![WindowsTerminal_rb21nChhHC](https://user-images.githubusercontent.com/11845298/187311046-48f0b9b3-ebea-4ef4-bf8f-61a775b3bff2.png)

### Expected Behavior

New project created

### Environment

OS: Windwos 11, Window 10
Actionhero Verision: 28.1.11
Nodejs: 14.20.0

**Comment by YamCrack** [comment]
the command works fine on actionhero 28.1.9

**Comment by evantahler** [comment]
Hi!

Can you confirm that the directory you tried `actionhero generate` in is empty?  Also, run `npx actionhero --version` to confirm which version you have locally.

I have no access to a windows machine to do debug this... so let me know if you are able to work on this issue yourself!

**Comment by YamCrack** [comment]
yes i have tried with empty directory and after npm i -s actionhero, none of them works, i can try to fix it.

**Comment by YamCrack** [comment]
I found the problem is the update of glob from 7.20 to 8.0.1

Since glob 7.2.1 backslash “\” is not supported and it only uses slash “/”,  everytime something like this is used:

`glob.sync(path.join(configPath, “**“, “**/*(*.js|*.ts)“))`

path.join adds a backslash. Therefore, the path is no longer valid. If you agree, we can change it to:

`glob.sync(path.join(configPath, “**“, “**/*(*.js|*.ts)“), { windowsPathsNoEscape: true })`

or join the paths manually.

Please let me know your thoughts.

**Comment by evantahler** [comment]
That's a shame that `windowsPathsNoEscape` isn't automatically enabled if a windows environment is detected.  Ideally, that would be a feature added to glob itself.  If that isn't possible, I guess we could wrap it in a utility... 

Can you try working with the glob maintainers first to create a "windows compat" mode?

**Comment by YamCrack** [comment]
There are issues related to this problem and they are refusing to change it. They recommend doing something like this:

`path.join(__dirname, '*.txt').split(path.sep).join("/")`

sorry for my bad english

**Comment by evantahler** [comment]
Can you link the conversation in the Glob repo please?  I wonder if they make good points that we should follow as well.

**Comment by YamCrack** [comment]
sure, there is:

https://github.com/isaacs/node-glob/issues/480
https://github.com/isaacs/node-glob/issues/468
https://github.com/isaacs/node-glob/issues/419

-- we can write a utility function that check por path.sep, and change the \\ to /.

**Comment by evantahler** [comment]
This conversation does a good job of explaining why replacing the slashes probably isn't a good idea - https://github.com/isaacs/node-glob/issues/468

I think the path forward is to replace all uses in the project of `glob`` with `safeGlob()` which internally attempts to detect which OS the project is running on.  If windows is detected, then we enable `windowsPathsNoEscape` as we call into glob.

```ts

function safeGlobSync(match: string) { 
  const isWindows: process.platform === "win32" || process.platform === "win64";
  return glob.sync(match, {windowsPathsNoEscape: isWindows})
} 

```

**Comment by YamCrack** [comment]
i did a PR, let me know your thoughts

https://github.com/actionhero/actionhero/pull/2278/commits/398241e44f55e9004745d254dec90d3ff4a7daed

**Comment by YamCrack** [comment]
Ia have been pull new changes:
 - test for safeGlobSync
 - pettify for lint faling files,
