### ISSUE TITLE
[Bug]: Pass config object to actionhero start method. 

### ISSUE THREAD

**Issue by dturton** [actionhero/actionhero#2345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The documentation states we can pass a config object to start method of actionhero but the current implementation doesn't expect any parameters. [](https://www.actionherojs.com/tutorials/config)

### Expected Behavior

Should be able to pass the custom config object. 

### Environment

 "actionhero": "^28.2.1",

**Comment by evantahler** [comment]
Oof, that's a mistake in the docs.  We've remove that in favor of having only one clear way to configure actionhero - via the configs!  This way, you'll get stronger typing and less surprises. 

Can you point me to where that is in the docs so I can remove it?

**Comment by dturton** [comment]
Sure this. I forgot to include it before. https://www.actionherojs.com/tutorials/config.

line -- options passed in to boot with actionhero.start({configChanges: configChanges})

Thanks!

**Comment by evantahler** [comment]
Thank you! https://github.com/actionhero/www.actionherojs.com/commit/b37ad55128b111a0d6069d839dc51761758aecd8
