### ISSUE TITLE
[Feature]: integration with async local storage

### ISSUE THREAD

**Issue by IgorHulyaschy** [actionhero/actionhero#2385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hello, I need help, I want to use AsyncLocalStorage with actionhero

**Comment by IgorHulyaschy** [comment]
here is the discussion: https://github.com/actionhero/actionhero/discussions/2384

**Comment by evantahler** [comment]
Closed via discussion.
