### ISSUE TITLE
[Bug]: Cache inconsistency

### ISSUE THREAD

**Issue by rogorman9** [actionhero/actionhero#2540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If two Actions are working with the same value in the cache at the same time, it's possible to get some inconsistent behavior. I was load testing a new application I wrote with Actionhero and was able to reproduce this fairly regularly. 

Example:
* The cache holds the value `0` at `key`
* Action A saves `1` to `key`
* At almost exactly the same time, Action B loads `key` from the cache
* B gets `0` back just before A saves `1`
* A second later, loading `key` from the cache returns `0`

### Expected Behavior

I believe this line should be removed: https://github.com/actionhero/actionhero/blob/main/src/modules/cache.ts#L219. With that in place, it's possible for a call to `cache.save` to resolve and then have the value it just saved overwritten immediately by another call to `cache.load` on the same node. 

I'd be happy to open a PR for this, if that helps. I tried to join the Actionhero Slack, but https://slack.actionherojs.com/ is not responding.

### Environment

OSX
Actionhero version 28.3.3
Node.js version 18.16.0

**Comment by evantahler** [comment]
A contribution would be great!
Ideally, I think a redis pipeline should be used to contain the read and write in a single transaction. 

I'll look into the slack server later today.

**Comment by rogorman9** [comment]
It seems a bit counterintuitive to me that `cache.load` is writing to Redis at all. Is there some other issue that's being solved for by that?

**Comment by evantahler** [comment]
(I think the slack redirect is fixed! thanks for letting me know)

**Comment by evantahler** [comment]
For contributing, @rogorman9 please make a fork and submit a pull request!

**Comment by evantahler** [comment]
The reason for the write is that we want to update the `readAt` timestamp, which is used for expiration https://github.com/actionhero/actionhero/blob/main/src/modules/cache.ts#L201
