### ISSUE TITLE
[Bug]: POST action with array input - only the last value is keeped

### ISSUE THREAD

**Issue by lbrulebois** [actionhero/actionhero#2834]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Upgrading from version **29.2.0** to >= **29.3.0** 

Using the sample action below : 
```typescript
export class ListAction extends Action {

    constructor() {
        super();
        this.name = "listaction";
        this.description = "Custom list action";
        this.inputs = {
            fruits: { required: true, validator: (v: any) => Array.isArray(v) }
        };
    }

    async run(data: ActionProcessor<ListAction>) {
        return { "fruits": data.params.fruits };
    }

}
```

Executing the action like this : 
```shell
curl --location 'http://localhost/api/demo' \
--header 'Content-Type: application/json' \
--data '{
    "fruits": [ "a", "b", "c", "d" ]
}'
```

With ActionHeroJS (**29.2.0**) the result was : 
```text
HTTP/200 OK
{ "fruits": [ "a", "b", "c", "d" ] }
```

With ActionHeroJS (>= **29.3.0**) the result is : 
```text 
HTTP/500 Internal Server Error 
{ "error": "Input for parameter \"fruits\" failed validation!" }
```

### Expected Behavior

With the previous sample action, the result with ActionHeroJS (>= **29.3.0**) must be the same with ActionHeroJS (**29.2.0**) : 
```text
HTTP/200 OK
{ "fruits": [ "a", "b", "c", "d" ] }
```

### Stack Trace

```markdown
2024-07-28T09:06:35.563Z - error: [ action @ web ] to=::1 action=listaction params={"action":"listaction","apiVersion":1,"fruits":"d"} duration=0 method=POST pathname=/api/demo error=Error: Input for parameter "fruits" failed validation! stack=Error: Input for parameter "fruits" failed validation!
    at ActionProcessor.validateParam (/Users/9202150m/Documents/projects/gasper/back/node_modules/actionhero/dist/classes/actionProcessor.js:254:55)
    at ActionProcessor.validateParams (/Users/9202150m/Documents/projects/gasper/back/node_modules/actionhero/dist/classes/actionProcessor.js:287:13)
    at ActionProcessor.runAction (/Users/9202150m/Documents/projects/gasper/back/node_modules/actionhero/dist/classes/actionProcessor.js:336:13)
    at WebServer.processAction (/Users/9202150m/Documents/projects/gasper/back/node_modules/actionhero/dist/classes/server.js:113:22)
```

### Environment

- Actionhero : >= **29.3.0**
- Node.js : **21.3.0**

### Additional context

The problem seems to be linked to the update of `src/servers/web.ts` line **732** to **760**.
If I comment the validator function like below : 
```typescript
export class ListAction extends Action {

    constructor() {
        super();
        this.name = "listaction";
        this.description = "Custom list action";
        this.inputs = {
            fruits: { required: true } /* validator: (v: any) => Array.isArray(v) */
        };
    }

    async run(data: ActionProcessor<ListAction>) {
        return { "fruits": data.params.fruits };
    }

}
```

With ActionHeroJS (>= **29.3.0**) the result is now : 
```text 
HTTP/200 OK
{ "fruits": "d" }
```
The array is replaced by the last value

**Comment by evantahler** [comment]
Thank you for the through reproduction steps! 

The good new is that this is a very easy fix - in your `config/servers/web.ts` add `multiples:true` to the `formOptions` (`config.servers.web.formOptions.multiples=true`).  It looks like the default options for formidable (the form parsing library we use) may have changed. Do you think we should set this as a default, e.g. https://github.com/actionhero/actionhero/pull/2835?

**Comment by evantahler** [comment]
Edit - this would be a breaking change, so never mind

**Comment by ricardograca-scratch** [comment]
I'm setting the `multiples: true` option and the unexpected behavior is not fixed. I'm using the latest version of Actionhero.

**Comment by evantahler** [comment]
We've got a test that confirms this behavior - https://github.com/actionhero/actionhero/blob/main/__tests__/servers/web/enableMultiples.ts#L29

Can you share a repo that reproduces the error

**Comment by ricardograca-scratch** [comment]
Sorry, it was a false alarm. I had an invalid web config file since I got here migrating from an older version, and the defaults from actionhero were being picked up instead. That still means this upgrade of formidable was a breaking change, so not sure if fixing the original breaking change and making `multiples: true` the default would also constitute a breaking change or just a restitution of the expected behavior.
