### ISSUE TITLE
Feature: Ability to test action middleware

### ISSUE THREAD

**Issue by NamespaceValentine** [actionhero/actionhero#970]
Feature: Ability to test middleware
Can currently test actions and tasks with the specHelper, but cant test middleware
- ActionHero Version: `15.1.0`
- Node.js Version: `4.5.0`
- Operating System `OSX`
# Steps to reproduce your issue
- Make a new actionhero project with `./node_modules/.bin/actionhero generate`
- Create an initializer to add a middleware
- In testing framework, try using specHelper.runAction with middleware name
- Get error Error: unknown action or invalid apiVersion

**Comment by evantahler** [comment]
Can you please provide examples of your middleware (I assume action middleware?) and your test action?  

This example project shows the spec helper using action middleware:
- https://github.com/evantahler/actionhero-angular-bootstrap-cors-csrf/blob/master/test/test.js#L26-L32
- https://github.com/evantahler/actionhero-angular-bootstrap-cors-csrf/blob/master/initializers/session.js#L49-L70

**Comment by NamespaceValentine** [comment]
The trouble is that, yes, I can test my middleware with an action, but I cannot test my middleware by itself. For instance, this works:

```
// initializers/middleware.js
var authToken = function(api) {
  return {
    name: 'authToken',
    preProcessor: function(data, next){
      try {
        //Do stuff
      } catch (e) {
        data.connection.rawConnection.responseHttpCode = 400;
        data.response.errors = [e];
        next();
      }
    }
  }
};

module.exports = {
  testAuth: authToken,

  initialize: function(api, next){
    api.actions.addMiddleware(authToken(api));
    next();
  }
}; 
```

```
// actions/auth.js
exports.getLookupSelf = {
  name: 'getLookupSelf',
  description: 'I return metadata about the given token',

  outputExample: {},

  inputs: {
  },

  middleware:["authToken"],

  run: function(api, data, next){
    data.response.data = {};
    next();
  }

};
```

```
// tests/middleware.js
var should = require('should');
var actionheroPrototype = require('actionhero').actionheroPrototype;
var actionhero = new actionheroPrototype();
var api;

describe('middleware', function(){

    before(function(done){
      actionhero.start(function(error, a){
        api = a;
        done();
      })
    });

    after(function(done){
      actionhero.stop(function(error){
        done();
      });
    });

    it('should allow ingress from env variable token', function(done){
      testConnection.rawConnection.req = {headers:{'someheader': 'somevalue'}}
      testConnection.rawConnection.responseHeaders = [];
      api.specHelper.runAction('getLookupSelf, testConnection, function(response){
        should.not.exist(response.errors);
        done();
      });

    });
```

However, if I want to test just the middleware without the getLookupSelf call (so I can test that the middleware itself is doing what it should without getLookupSelf possibly messing up the test), the only way I can see to currently do that is:

```
// tests/middleware.js

var should = require('should');
var actionheroPrototype = require('actionhero').actionheroPrototype;
var actionhero = new actionheroPrototype();
var api;
var authMiddleware = require('../initializers/middleware').testAuth;

describe('middleware', function(){

    before(function(done){
      actionhero.start(function(error, a){
        api = a;
        done();
      })
    });

    after(function(done){
      actionhero.stop(function(error){
        done();
      });
    });

    it('should allow ingress from env variable token', function(done){
      var testConnection = new api.specHelper.connection();
      var authMiddlewareInitialized = authMiddleware(api).preProcessor;

      testConnection.rawConnection.req = {headers:{'someheader': 'somevalue'}}
      var data = {connection: testConnection, response:{errors:null}};
      authMiddlewareInitialized(data, function(){
        should.not.exist(data.response.errors);
        done();
      });

    });
});
```

**Comment by NamespaceValentine** [comment]
I would prefer that we have a way of doing this through the specHelper, rather than having to manually fetch the portion of the middleware we want to run and directly calling it.

**Comment by evantahler** [comment]
I understand your request now, thanks!

Since middleware can work on actions both before and after the action's execution, how would you propose to test the "after" case?  I think in either way, we would need a built-in `no-op` action which could be called, and then you could amend your middleware on to it for this one request. 

One note, you can always access the middleware already (not needing to re-require it) via `api.actions.middleware`

**Comment by NamespaceValentine** [comment]
Ideally the test helper would consider the middleware agnostic of where it appears in the flow, pre or post. It should be able to take in an expected state (read payload and anything else the middleware reads) and run the middleware, then test its output to either the next step (how does it affect the response and what is the modified state after the middleware has run.

**Comment by evantahler** [comment]
Cool.  Is this a pull request you are intending on writing yourself, or are you looking for help?  Have you joined our [slack team](http://slack.actionherojs.com) yet?  That's best place to ask for help as you are working on a pull request.

**Comment by NamespaceValentine** [comment]
Oh, unfortunately I dont have the bandwitdth to contribute for it, I'm just submitting the feature request and use case. I currently have the workaround for it, as I showed in the OP.

**Comment by evantahler** [comment]
closing due to lack of interest
